<?php

namespace Database\Seeders;

use App\Models\Publisher;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PublisherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table((new \App\Models\Publisher())->getTable())->truncate();
        
        $publishers = array(
            array('id' => '1','publish_name' => 'دار الفراشة للطباعة والنشر والتوزيع','publish_address' => '' ),
            array('id' => '4','publish_name' => 'Baker Book House','publish_address' => 'Michigan' ),
            array('id' => '5','publish_name' => 'Zondervan Publishing House','publish_address' => 'Michigan' ),
            array('id' => '6','publish_name' => 'Human sciences Press','publish_address' => 'New Yourk' ),
            array('id' => '7','publish_name' => 'American Psychiatric Association','publish_address' => 'USA' ),
            array('id' => '8','publish_name' => 'Word Publishing','publish_address' => 'London' ),
            array('id' => '9','publish_name' => 'InterVarsity Press','publish_address' => 'Illinois' ),
            array('id' => '10','publish_name' => 'Good Samaritan Ministries','publish_address' => 'USA' ),
            array('id' => '11','publish_name' => 'NavPress','publish_address' => 'USA' ),
            array('id' => '12','publish_name' => 'Kingsway Publications','publish_address' => 'Great Britain' ),
            array('id' => '13','publish_name' => 'Regal Books','publish_address' => 'USA' ),
            array('id' => '14','publish_name' => 'Walker & Company','publish_address' => 'New Yourk' ),
            array('id' => '15','publish_name' => 'Brooks/Cole Publishing Company','publish_address' => 'California' ),
            array('id' => '16','publish_name' => 'Guideposts','publish_address' => 'New Yourk' ),
            array('id' => '17','publish_name' => 'Grove Press, INC.','publish_address' => 'New York' ),
            array('id' => '18','publish_name' => 'Rawson, Wade Publishers, INC.','publish_address' => 'New Yourk' ),
            array('id' => '19','publish_name' => 'Dell Publishing Co., Inc.','publish_address' => 'New Yourk' ),
            array('id' => '20','publish_name' => 'Harper & Row, Publishers','publish_address' => 'New Yourk' ),
            array('id' => '21','publish_name' => 'Simon & Schuster','publish_address' => 'New Yourk' ),
            array('id' => '22','publish_name' => 'Basic Books, Inc., Publishers','publish_address' => 'New Yourk' ),
            array('id' => '23','publish_name' => 'Jason Aronson Inc.','publish_address' => 'London' ),
            array('id' => '24','publish_name' => 'Hodder and Stoughton','publish_address' => 'London' ),
            array('id' => '25','publish_name' => 'Christian Press','publish_address' => 'Great Britain' ),
            array('id' => '26','publish_name' => 'Basil Blackwell','publish_address' => 'USA' ),
            array('id' => '27','publish_name' => 'Prentice-Hall, Inc.,','publish_address' => 'New Jersey' ),
            array('id' => '28','publish_name' => 'Macdonald & Evans LTD','publish_address' => '' ),
            array('id' => '29','publish_name' => 'Cambridge University Press','publish_address' => 'New Your' ),
            array('id' => '30','publish_name' => 'The Westminster Press','publish_address' => 'Philadelphia' ),
            array('id' => '31','publish_name' => 'D. Van Nostrand Company, INC.','publish_address' => 'London' ),
            array('id' => '32','publish_name' => 'Cokesbury Press','publish_address' => 'USA' ),
            array('id' => '33','publish_name' => 'Fawcett Publicatios, INC.','publish_address' => 'USA' ),
            array('id' => '34','publish_name' => 'Houghton Mifflin Company','publish_address' => 'New Yourk' ),
            array('id' => '35','publish_name' => 'Harvest/HBJ Book','publish_address' => 'New Yourk' ),
            array('id' => '36','publish_name' => 'W. W. Norton & Company. INC.','publish_address' => 'New Yourk' ),
            array('id' => '37','publish_name' => 'A Toughstone Book','publish_address' => 'New Yourk' ),
            array('id' => '38','publish_name' => 'Springer Publishing Company','publish_address' => 'New Yourk' ),
            array('id' => '40','publish_name' => 'Routledge & Kegan Paul LTD','publish_address' => 'Great Britain' ),
            array('id' => '41','publish_name' => 'Highland Books','publish_address' => 'Great Britain' ),
            array('id' => '42','publish_name' => 'SCM Press LTD','publish_address' => 'London' ),
            array('id' => '44','publish_name' => 'Avon Books','publish_address' => 'New Yourk' ),
            array('id' => '45','publish_name' => 'Penguin Books','publish_address' => 'England' ),
            array('id' => '46','publish_name' => 'Augsburg Publishing House','publish_address' => 'Minneapolis' ),
            array('id' => '47','publish_name' => 'Scripture Press Foundation','publish_address' => 'England' ),
            array('id' => '48','publish_name' => 'Bridge Publishing, INC.','publish_address' => 'USA' ),
            array('id' => '49','publish_name' => 'Victor Books','publish_address' => 'England' ),
            array('id' => '51','publish_name' => 'The Macmillan company','publish_address' => 'New Yourk' ),
            array('id' => '52','publish_name' => 'Bethany House Publishers','publish_address' => 'USA' ),
            array('id' => '53','publish_name' => 'Multnomah Press','publish_address' => 'Portland' ),
            array('id' => '54','publish_name' => 'Harper Paperbacks','publish_address' => 'New Yourk' ),
            array('id' => '55','publish_name' => 'Servant Publications','publish_address' => 'Michigan' ),
            array('id' => '56','publish_name' => 'Rapha Publishing/ word, Inc.','publish_address' => 'Texas' ),
            array('id' => '57','publish_name' => 'Aglow Publications','publish_address' => 'Washington' ),
            array('id' => '58','publish_name' => 'Health Communications, INC.','publish_address' => 'Florida' ),
            array('id' => '59','publish_name' => 'A Dell Book','publish_address' => 'USA' ),
            array('id' => '60','publish_name' => 'Sheldon Press','publish_address' => 'London' ),
            array('id' => '61','publish_name' => 'Sovereign World Ltd','publish_address' => 'England' ),
            array('id' => '62','publish_name' => 'A Division of Thomas Publishers','publish_address' => 'USA' ),
            array('id' => '63','publish_name' => 'Intimacy Press','publish_address' => 'Texas' ),
            array('id' => '64','publish_name' => 'Ave Maria Press','publish_address' => 'Notre Dame' ),
            array('id' => '65','publish_name' => 'Fleming H. Revell company','publish_address' => 'New Jersey' ),
            array('id' => '66','publish_name' => 'Yokefellow Press','publish_address' => 'Burlingame, CA 94010' ),
            array('id' => '67','publish_name' => 'Tyndale House Publishers','publish_address' => 'Wheaton, Illinois' ),
            array('id' => '68','publish_name' => 'David C. Cook Publishing Co.','publish_address' => 'Elgin, Illinois' ),
            array('id' => '69','publish_name' => 'Thomas Nelson, Inc','publish_address' => 'Nashville' ),
            array('id' => '70','publish_name' => 'Heritage House Publications','publish_address' => 'Colorado' ),
            array('id' => '71','publish_name' => 'Prelude Press','publish_address' => 'California' ),
            array('id' => '72','publish_name' => 'Bantam Books','publish_address' => 'New Yourk' ),
            array('id' => '73','publish_name' => 'Life Skills','publish_address' => 'USA' ),
            array('id' => '74','publish_name' => 'Christian Herald Books','publish_address' => 'New Yourk' ),
            array('id' => '75','publish_name' => 'The Seabury Press','publish_address' => 'New Yourk' ),
            array('id' => '76','publish_name' => 'Harvest House Publishers','publish_address' => 'California' ),
            array('id' => '77','publish_name' => 'International Paperback','publish_address' => 'Sydney' ),
            array('id' => '78','publish_name' => 'Pocket Books','publish_address' => 'New Yourk' ),
            array('id' => '79','publish_name' => 'Research Press','publish_address' => 'Illinois' ),
            array('id' => '80','publish_name' => 'Northfield Publishing','publish_address' => 'Chicago' ),
            array('id' => '81','publish_name' => 'Little Ones Books','publish_address' => 'Canada' ),
            array('id' => '82','publish_name' => 'John Knox Press','publish_address' => 'Atlanta' ),
            array('id' => '83','publish_name' => 'Perigee Book','publish_address' => 'New Yourk' ),
            array('id' => '84','publish_name' => 'A Tom Doherty Associates Book','publish_address' => 'New Yourk' ),
            array('id' => '85','publish_name' => 'Doubleday','publish_address' => 'New Yourk' ),
            array('id' => '86','publish_name' => 'Howthorn Books, INC. Publishers','publish_address' => 'New Yourk' ),
            array('id' => '87','publish_name' => 'Monarch Publications Ltd','publish_address' => 'UK' ),
            array('id' => '88','publish_name' => 'Creation House','publish_address' => 'Florida' ),
            array('id' => '89','publish_name' => 'McGraw-Hill Book Company','publish_address' => 'New Yourk' ),
            array('id' => '90','publish_name' => 'Launch Press','publish_address' => 'Rockville' ),
            array('id' => '91','publish_name' => 'Alcoholics Anonymous, World Services, Inc','publish_address' => 'New Yourk' ),
            array('id' => '93','publish_name' => 'Addison-Wesley Publishing Company','publish_address' => 'USA' ),
            array('id' => '94','publish_name' => 'Churchill Livingstone','publish_address' => 'New Yourk' ),
            array('id' => '95','publish_name' => 'Sex & Love Addicts Anonymous','publish_address' => 'USA' ),
            array('id' => '96','publish_name' => 'Hazelden','publish_address' => 'Minnesota' ),
            array('id' => '97','publish_name' => 'Hesperian Foundation','publish_address' => 'California' ),
            array('id' => '98','publish_name' => 'Faith Library Publications','publish_address' => 'USA' ),
            array('id' => '99','publish_name' => 'Winston Press','publish_address' => 'Minneapolis' ),
            array('id' => '100','publish_name' => 'Berkely Books','publish_address' => 'New Yourk' ),
            array('id' => '101','publish_name' => 'The Upper Room','publish_address' => 'Nashville' ),
            array('id' => '102','publish_name' => 'Abingdon Press','publish_address' => 'New Yourk' ),
            array('id' => '103','publish_name' => 'Fawcett Columbine Book','publish_address' => 'New Yourk' ),
            array('id' => '104','publish_name' => 'Fforbez Publications Ltd.','publish_address' => 'Canada' ),
            array('id' => '105','publish_name' => 'Darton, Longman and Todd','publish_address' => 'London' ),
            array('id' => '106','publish_name' => 'A Dayspring Edition','publish_address' => 'New Yourk' ),
            array('id' => '107','publish_name' => 'Business Books','publish_address' => 'London' ),
            array('id' => '108','publish_name' => 'Faith Today Publications','publish_address' => '' ),
            array('id' => '109','publish_name' => 'William Collins Sons & Co Ltd','publish_address' => 'Great Britain' ),
            array('id' => '110','publish_name' => 'Whitaker House','publish_address' => 'USA' ),
            array('id' => '111','publish_name' => 'Harold Shaw Publishers','publish_address' => 'Wheaton, Illinois' ),
            array('id' => '112','publish_name' => 'William B. Eerdmans Publishing Company','publish_address' => 'Michigan' ),
            array('id' => '113','publish_name' => 'Standard Publishing','publish_address' => 'Ohio' ),
            array('id' => '114','publish_name' => 'Hyperion','publish_address' => 'New Yourk' ),
            array('id' => '115','publish_name' => 'Multnomah Publishers, Inc.','publish_address' => 'Oregon' ),
            array('id' => '116','publish_name' => 'Maadi Comunity Church','publish_address' => 'Cairo, Egypt' ),
            array('id' => '117','publish_name' => 'Marshall Morgan & Scott','publish_address' => '' ),
            array('id' => '118','publish_name' => 'Hazell Watson & Viney Limited','publish_address' => 'Aylesburg' ),
            array('id' => '119','publish_name' => 'Discovery House Publishers','publish_address' => 'Michigan' ),
            array('id' => '120','publish_name' => 'Crossway Books','publish_address' => 'Illinois' ),
            array('id' => '121','publish_name' => 'Grolier Enterpries Inc.','publish_address' => 'Danbury' ),
            array('id' => '122','publish_name' => 'Living Skills Press','publish_address' => 'California' ),
            array('id' => '123','publish_name' => 'CAPS','publish_address' => '' ),
            array('id' => '124','publish_name' => 'Moody Press','publish_address' => 'Chicago' ),
            array('id' => '125','publish_name' => 'The Seed Sowers','publish_address' => 'Texas' ),
            array('id' => '126','publish_name' => 'Christian Publications, Inc.','publish_address' => 'USA' ),
            array('id' => '127','publish_name' => 'WS Bookwell','publish_address' => 'Finland' ),
            array('id' => '128','publish_name' => 'Harper Collins Publishers','publish_address' => 'London' ),
            array('id' => '129','publish_name' => 'Butterworths','publish_address' => 'London' ),
            array('id' => '130','publish_name' => 'Oxford University Press','publish_address' => 'New Yourk' ),
            array('id' => '131','publish_name' => 'Caleb International Ministries','publish_address' => '' ),
            array('id' => '132','publish_name' => 'دار الحرية','publish_address' => '14 ش جواد حسني - القاهرة' ),
            array('id' => '133','publish_name' => 'دار أخبار اليوم','publish_address' => 'القاهرة' ),
            array('id' => '134','publish_name' => 'لجنة خلاص النفوس للنشر','publish_address' => '12 ش قطة بشبرا مصر' ),
            array('id' => '135','publish_name' => 'دار زهراء الشرق','publish_address' => '16 ش محمد فريد' ),
            array('id' => '136','publish_name' => 'الهيئة المصرية العامة للكتاب','publish_address' => '1194 كورنيش النيل -رملة بولاق-مبيني الهيئة العامة للكتاب' ),
            array('id' => '137','publish_name' => 'مكتبة النهضة المصرية','publish_address' => '9 ش عدلي باشا - القاهرة' ),
            array('id' => '138','publish_name' => 'الدار المصرية اللبنانية','publish_address' => '16ش عبد الخالق ثروت - القاهرة' ),
            array('id' => '139','publish_name' => 'المجلس الوطني للثقافة والفنون والآداب','publish_address' => 'ص. ب 23996 الصفاة - الكويت' ),
            array('id' => '140','publish_name' => 'دار المعارف','publish_address' => '1119 ش كورنيش النيل - القاهرة' ),
            array('id' => '141','publish_name' => 'دار ومكتبة الهلال','publish_address' => 'ص. ب 155003 بيروت' ),
            array('id' => '142','publish_name' => 'دار الفجر للنشر والتوزيع','publish_address' => '4 ش هاشم الأشقر - النزهة الجديدة'  ),
            array('id' => '143','publish_name' => 'دار الهلال','publish_address' => '16 ش محمد عز العرب - القاهرة' ),
            array('id' => '144','publish_name' => 'دار مصر للطباعة','publish_address' => '37 ش كامل صدقي - الفجالة' ),
            array('id' => '145','publish_name' => 'دار قباء للطباعة والنشر والتوزيع','publish_address' => 'القاهرة' ),
            array('id' => '146','publish_name' => 'الدار العربية للعلوم','publish_address' => 'ص. ب 13/5574 بيروت' ),
            array('id' => '147','publish_name' => 'لوجوس برنت سنتر','publish_address' => 'ص. ب 2455 الحرية' ),
            array('id' => '148','publish_name' => 'دار الآفاق الجديدة','publish_address' => 'بيروت' ),
            array('id' => '149','publish_name' => 'مكتبة الأنجلو المصرية','publish_address' => '165 ش محمد فريد - القاهرة' ),
            array('id' => '150','publish_name' => 'دار الفكر العربي','publish_address' => '11 ش جواد حسني - القاهرة' ),
            array('id' => '151','publish_name' => 'شعاع للنشر والعلوم','publish_address' => 'سوريا - حلب' ),
            array('id' => '152','publish_name' => 'المجلس الأعلى للثقافة','publish_address' => 'شارع الجبلاية بالأوبرا - القاهرة' ),
            array('id' => '153','publish_name' => 'دار الثقافة','publish_address' => 'ص. ب 1298 القاهرة' ),
            array('id' => '155','publish_name' => 'مكتبة الخانجي','publish_address' => 'ص. ب 1375القاهرة' ),
            array('id' => '157','publish_name' => 'دار النشر الأسقفية','publish_address' => 'ص. ب 4 قصور الشوام - القاهرة' ),
            array('id' => '158','publish_name' => 'دار النشر المعمدانية','publish_address' => 'ص. ب 2026 - 11 - بيروت' ),
            array('id' => '159','publish_name' => 'مكتبة المحبة','publish_address' => 'ص. ب 12 قصورة الشوام - القاهرة' ),
            array('id' => '160','publish_name' => 'دار الجيل للطباعة','publish_address' => '14 قصر الؤلؤة - الفجالة' ),
            array('id' => '161','publish_name' => 'دار منشورات النفير','publish_address' => 'ص. ب 50364 فرن الشباك - بيروت' ),
            array('id' => '162','publish_name' => 'جمعية كاريتاس','publish_address' => 'مصر' ),
            array('id' => '163','publish_name' => 'شذا دوس','publish_address' => '2 ش السباق - مصر الجديدة' ),
            array('id' => '164','publish_name' => 'المؤسسة العربية الحديثة للطبع والنشر والتوزيع','publish_address' => '10 ش كامل صدقي - الفجالة' ),
            array('id' => '165','publish_name' => 'دار غريب للطباعة والنشر والتوزيع','publish_address' => '12 ش نوبار لاظوغلي' ),
            array('id' => '167','publish_name' => 'أرساني جرافيك','publish_address' => '26 ش عبد الله صالح - شبرا' ),
            array('id' => '168','publish_name' => 'مكتبة الشباب','publish_address' => 'الأنبا رويس - العباسية' ),
            array('id' => '169','publish_name' => 'نهضة مصر للنشر والتوزيع','publish_address' => '18 ش صدقي كامل - الفجالة' ),
            array('id' => '170','publish_name' => 'مكتبة أسقفية الشباب','publish_address' => 'ص. ب 15 الظاهر - القاهرة' ),
            array('id' => '171','publish_name' => 'الدار الدولية للنشر والتوزيع','publish_address' => 'القاهرة' ),
            array('id' => '172','publish_name' => 'دار النهضة العربية','publish_address' => '33 ش عبد الخالق ثروت - القاهرة' ),
            array('id' => '173','publish_name' => 'مطابع الزهراء للإعلام العربي','publish_address' => 'مدينة نصر - القاهرة' ),
            array('id' => '174','publish_name' => 'الكنيسة الإنجيلية بقصر الدوبارة','publish_address' => 'جاردن سيتي - القاهرة' ),
            array('id' => '175','publish_name' => 'مطبوعات إيجلز','publish_address' => 'ص. ب 1101 هليوبوليس بحري - القاهرة' ),
            array('id' => '176','publish_name' => 'مطبعة الأمل','publish_address' => '' ),
            array('id' => '177','publish_name' => 'منشورات بحسون الثقافية','publish_address' => 'بيروت - لبنان' ),
            array('id' => '178','publish_name' => 'دار الشروق','publish_address' => '8 ش سيبويه المصري - القاهرة' ),
            array('id' => '179','publish_name' => 'دار الطباعة القومية','publish_address' => 'الفجالة' ),
            array('id' => '180','publish_name' => 'دار القلم','publish_address' => 'الكويت' ),
            array('id' => '181','publish_name' => ' دار الكلمة','publish_address' => '23 ش عين شمس - القاهرة' ),
            array('id' => '182','publish_name' => 'مطبعة الهندي','publish_address' => 'دمشق' ),
            array('id' => '183','publish_name' => 'دار الجيل','publish_address' => 'بيروت' ),
            array('id' => '184','publish_name' => 'دار النهضة العربية للطباعة والنشر','publish_address' => 'ص. ب 110749 - بيروت' ),
            array('id' => '185','publish_name' => 'دار الطليعة للطباعة والنشر','publish_address' => 'بيروت' ),
            array('id' => '186','publish_name' => 'دار الحوار للنشر والتوزيع','publish_address' => 'اللاذقية - سوريا' ),
            array('id' => '187','publish_name' => 'هلا للنشر والتوزيع','publish_address' => '6 ش الدكتور حجازي - الجيزة' ),
            array('id' => '188','publish_name' => 'دار المشرق','publish_address' => 'ص. ب 946 - بيروت' ),
            array('id' => '189','publish_name' => 'عالم الكتب','publish_address' => '16 ش جواد حسنى - القاهرة' ),
            array('id' => '190','publish_name' => 'مكتبة العبيكان','publish_address' => 'المملكة العربية السعزدية' ),
            array('id' => '191','publish_name' => 'مركز الدلتا للطباعة','publish_address' => 'إسكندرية' ),
            array('id' => '192','publish_name' => 'الرسالة الدولية للإعلان','publish_address' => 'القاهرة' ),
            array('id' => '193','publish_name' => 'مكتبة غريب','publish_address' => '301 ش كامل صدقي - الفجالة' ),
            array('id' => '194','publish_name' => 'دار الكتب والوثائق القومية','publish_address' => 'القاهرة' ),
            array('id' => '195','publish_name' => 'مكتبة الصفحات الهبية للنشر والتوزيع','publish_address' => 'المملكة العربية السعودية - الرياض' ),
            array('id' => '196','publish_name' => 'إيتراك للنشر والتوزيع','publish_address' => 'مصر الجديدة' ),
            array('id' => '197','publish_name' => 'دار الشايع للنشر','publish_address' => 'القاهرة - الكويت - أمستردام' ),
            array('id' => '198','publish_name' => 'مكتبة جرير','publish_address' => 'الرياض' ),
            array('id' => '199','publish_name' => 'جي سي سنتر','publish_address' => 'مصر الجديدة' ),
            array('id' => '200','publish_name' => 'دار التأليف والنشر للكنيسة الأسقية','publish_address' => '36 ش الجلاء - القاهرة' ),
            array('id' => '201','publish_name' => 'مكتبة المنار','publish_address' => 'مصر الجديدة' ),
            array('id' => '203','publish_name' => 'منشورات ينبوع الحياة','publish_address' => 'ص. ب 38 الكرك' ),
            array('id' => '204','publish_name' => 'دار السحاب للنشر والتوزيع','publish_address' => '8 شارع المدينة المنورة - القاهرة' ),
            array('id' => '205','publish_name' => 'أوفير للطباعة والنشر','publish_address' => 'عمان - الأردن' ),
            array('id' => '206','publish_name' => 'برنامج الأمم المتحدة الإنمائي','publish_address' => 'مركز التجارة العالمي' ),
            array('id' => '207','publish_name' => 'دار العالم العربي للطباعة','publish_address' => '23 ش الظاهر - القاهرة' ),
            array('id' => '208','publish_name' => 'منشورات الفردوس','publish_address' => 'الروضة - لبنان' ),
            array('id' => '209','publish_name' => 'غير معروف','publish_address' => '' ),
            array('id' => '210','publish_name' => 'دار الأمل للنشر والتوزيع','publish_address' => 'إربد - الأردن' ),
            array('id' => '211','publish_name' => 'مجلس كنائس الشرق الأوسط - لجنة الأسرة','publish_address' => 'مصر' ),
            array('id' => '213','publish_name' => 'جمعية تنظيم الأسرة','publish_address' => 'القاهرة' ),
            array('id' => '214','publish_name' => 'د. نبيل بشارة مرقص','publish_address' => '65 ش نخلة المطيعي - تريومف - مصر الجديدة' ),
            array('id' => '215','publish_name' => 'دار منهل الحياة','publish_address' => 'ص. ب 60 منصورية المتن - لبنان' ),
            array('id' => '216','publish_name' => 'الأسقفية العامة للمعادي وطرى ودار السلام','publish_address' => 'المعادي' ),
            array('id' => '217','publish_name' => 'دار الخيَال','publish_address' => 'المناره - بيروت'  ),
            array('id' => '218','publish_name' => 'الخدمات العالمية لجماعة جمعية مدمنو الخمر مجهولو الاسم','publish_address' => 'نيويورك' ),
            array('id' => '219','publish_name' => 'مؤسسة Grapevine التابعة لجمعية المدمنين المجهولين','publish_address' => 'نيويورك' ),
            array('id' => '220','publish_name' => 'المركز العربي الحديث','publish_address' => 'ميدان الإسماعيلية - مصر الجديدة' ),
            array('id' => '221','publish_name' => 'رابطة السيدات العامة','publish_address' => 'مصر' ),
            array('id' => '222','publish_name' => 'لجنة الأسرة بأسقفية الخدمات العامة الاجتماعية','publish_address' => '' ),
            array('id' => '223','publish_name' => 'جروس برس','publish_address' => 'طرابلس - لبنان' ),
            array('id' => '224','publish_name' => 'منشورات النور','publish_address' => 'بيروت - لبنان' ),
            array('id' => '226','publish_name' => 'منشورات المكتبة البولسية','publish_address' => 'بيروت - لبنان' ),
            array('id' => '227','publish_name' => 'ق. صموئيل رزفي إبراهيم','publish_address' => 'القاهرة' ),
            array('id' => '228','publish_name' => 'مؤسسة الأبحاث العربية','publish_address' => 'بيروت - لبنان' ),
            array('id' => '229','publish_name' => 'مكتبة النسر للطباعة','publish_address' => 'حلمية الزيتون - القاهرة' ),
            array('id' => '231','publish_name' => 'منشورات العالم العربي','publish_address' => 'بيروت - لبنان' ),
            array('id' => '232','publish_name' => 'راهبات مريم الإنجيليات','publish_address' => 'دار مشتات - ألمانيا الغربية' ),
            array('id' => '233','publish_name' => 'سمايل برس','publish_address' => 'القاهرة' ),
            array('id' => '234','publish_name' => 'جمعية الخدمة المسيحية العملية','publish_address' => '' ),
            array('id' => '235','publish_name' => 'الكنيسة الإنجيلية بالشرابية','publish_address' => 'القاهرة' ),
            array('id' => '237','publish_name' => 'فريق التسبيح','publish_address' => '' ),
            array('id' => '238','publish_name' => 'مطبوعات الشرق الأوسط','publish_address' => 'بيروت - لبنان' ),
            array('id' => '239','publish_name' => 'مطبعة دير القديس أنبا مقار','publish_address' => 'وادي النطرون' ),
            array('id' => '241','publish_name' => 'مركز المطبوعات المسيحية','publish_address' => 'بيروت - لبنان' ),
            array('id' => '242','publish_name' => 'مكتبة النيل المسيحية','publish_address' => 'القاهرة' ),
            array('id' => '243','publish_name' => 'جمعية الطب النفسي التطوري والعمل الجماعي','publish_address' => 'القاهرة' ),
            array('id' => '244','publish_name' => 'الجمعية المصرية لنشر المعرفة والثقافة العالمية','publish_address' => '' ),
            array('id' => '245','publish_name' => 'نادر جبرائيل حنا','publish_address' => '' ),
            array('id' => '246','publish_name' => 'وحيد رأفت زكي','publish_address' => '' ),
            array('id' => '248','publish_name' => 'د. سيد الهواري','publish_address' => '' ),
            array('id' => '249','publish_name' => 'عالم الكتب للنشر والتوزيع','publish_address' => 'بيروت - لبنان' ),
            array('id' => '250','publish_name' => 'دار الأصدقاء','publish_address' => 'بيروت - لبنان' ),
            array('id' => '251','publish_name' => 'كلية التجارة - جامعة عين شمس','publish_address' => '' ),
            array('id' => '252','publish_name' => 'د. عبد الفتاح دياب حسين','publish_address' => '' ),
            array('id' => '253','publish_name' => 'طارق الأجهوري','publish_address' => '' ),
            array('id' => '254','publish_name' => 'نبيل صبحي','publish_address' => '' ),
            array('id' => '255','publish_name' => 'الدار المصرية للنشر والتوزيع','publish_address' => 'نيقوسيا - قبرص' ),
            array('id' => '256','publish_name' => 'دار ومطابع المستقبل','publish_address' => 'الفجالة' ),
            array('id' => '257','publish_name' => 'مكتبة مدبولي','publish_address' => '6 ميدان طلعت حرب - القاهرة' ),
            array('id' => '258','publish_name' => 'مكتبة مصر','publish_address' => '3 ش كامل صدقي - الفجالة' ),
            array('id' => '259','publish_name' => 'مكتبة الآداب','publish_address' => '42 ميدان الأوبرا - القاهرة' ),
            array('id' => '260','publish_name' => 'مكتبة برهومة للنشر والتوزيع','publish_address' => 'عمان' ),
            array('id' => '261','publish_name' => 'دار الوفاء لدنيا الطباعة والنشر','publish_address' => 'إسكندرية' ),
            array('id' => '262','publish_name' => 'المنشورات المعمدانية','publish_address' => 'ص. ب 5232 بيروت' ),
            array('id' => '263','publish_name' => 'المؤسسة الجامعية للدراسات والنشر والتوزيع','publish_address' => 'بيروت - لبنان' ),
            array('id' => '264','publish_name' => 'دار الثقافة للطباعة والنشر','publish_address' => '21 ش كامل صدقي - الفجالة' ),
            array('id' => '265','publish_name' => 'دار التنوير للطباعة والنشر','publish_address' => 'بيروت - لبنان' ),
            array('id' => '266','publish_name' => 'دار شرقيات للنشر و التوزيع','publish_address' => '5 ش محمد صدقي- هدى شعراوى- باب اللوق'  ),
            array('id' => '267','publish_name' => 'مركز دراسات الوحدة العربية','publish_address' => 'بيروت - لبنان' ),
            array('id' => '268','publish_name' => 'مطبعة الدار المصرية','publish_address' => '22 ش سامي بالمالية - القاهرة' ),
            array('id' => '269','publish_name' => 'دار العالم الثالث','publish_address' => '32 صبري أبو علم - باب اللوق - القاهرة' ),
            array('id' => '270','publish_name' => 'خدمة المشورة والنضج المسيحي','publish_address' => 'شبرا' ),
            array('id' => '271','publish_name' => 'مكتبة الأخوة','publish_address' => '3 ش أنجه هانم - شبرا مصر' ),
            array('id' => '272','publish_name' => 'الكنيسة المركزية للمجمع','publish_address' => 'جزيرة بدران - شبرا مصر' ),
            array('id' => '273','publish_name' => 'مؤسسة القديس أنطونيوس - المركز الأرثوذكسي للدراسات الآبائية','publish_address' => 'مصر الجديدة' ),
            array('id' => '274','publish_name' => 'مكتبة مارجرجس','publish_address' => 'اسبورتنج - إسكندرية' ),
            array('id' => '275','publish_name' => 'فيلوباترون للترجمة والنشر','publish_address' => '' ),
            array('id' => '276','publish_name' => 'مجمع كنائس الإيمان بمصر','publish_address' => '' ),
            array('id' => '277','publish_name' => 'P.T.W','publish_address' => ''  ),
            array('id' => '278','publish_name' => 'كنيسة الاتحاد المسيحي الإنجيلية الوطنية','publish_address' => 'بيروت - لبنان' ),
            array('id' => '279','publish_name' => 'الرابطة الإنجيلية في الشرق الأوسط','publish_address' => '9أ شارع المسعود - العباسية- القاهرة' ),
            array('id' => '280','publish_name' => 'مجلس كنائس الشرق الأوسط - اللجنة المحلية لقسم الإيمان والوحدة','publish_address' => '' ),
            array('id' => '281','publish_name' => 'مكتبة المعارف','publish_address' => 'بيروت' ),
            array('id' => '282','publish_name' => 'شركة ماستر ميديا','publish_address' => 'عمارة برج الجزائر - المعادي' ),
            array('id' => '283','publish_name' => 'دار الغد للثقافة والنشر','publish_address' => '47 ش الفلكي - القاهرة' ),
            array('id' => '284','publish_name' => 'مكتبة الأخوة بأسيوط','publish_address' => '' ),
            array('id' => '285','publish_name' => 'الخدمات المسيحية للشرق الاوسط','publish_address' => '' ),
            array('id' => '286','publish_name' => 'كنيسة السيدة العذراء والأنبا أبرآم','publish_address' => 'إنجلترا' ),
            array('id' => '287','publish_name' => 'مجمع الكنائس في الشرق الأدنى','publish_address' => '' ),
            array('id' => '288','publish_name' => 'مطبعة د. فيكتور كيرلس','publish_address' => '' ),
            array('id' => '290','publish_name' => 'المجلس العام للكنائس الرسولية','publish_address' => 'المعادي' ),
            array('id' => '291','publish_name' => 'معهد تدريب القادة بالشرق الأوسط','publish_address' => '' ),
            array('id' => '292','publish_name' => 'مؤسسة روز اليوسف للصحافة والطباعة والنشر','publish_address' => 'القاهرة' ),
            array('id' => '293','publish_name' => 'شركة الحوار الثقافي','publish_address' => 'بيروت لبنان' ),
            array('id' => '295','publish_name' => 'الهيئة العامة لقصور الثقافة','publish_address' => '' ),
            array('id' => '296','publish_name' => 'منشورات دار مكتبة الحياة','publish_address' => 'بيروت - لبنان' ),
            array('id' => '297','publish_name' => 'كنيسة الإنجيلية بقصر الدوبارة وكلية فاريتاس','publish_address' => '' ),
            array('id' => '298','publish_name' => 'Pleasant Word','publish_address' => 'PO Box 428, Enumclaw' ),
            array('id' => '299','publish_name' => 'الهيئة المصرية العامة لدار الكتب والوثائق القومية','publish_address' => '' ),
            array('id' => '300','publish_name' => 'دار الثقافة المسيحية','publish_address' => 'ص ب1304' ),
            array('id' => '301','publish_name' => 'المركز العربى كاليفورنيا','publish_address' => 'كاليفورنيا' ),
            array('id' => '303','publish_name' => ' المكتبة الثقافية - بيروت','publish_address' => 'بيروت' ),
            array('id' => '309','publish_name' => ' Yale University Press','publish_address' => 'USA' ),
            array('id' => '311','publish_name' => ' Honor Books, Inc','publish_address' => '' ),
            array('id' => '312','publish_name' => ' Gramercy Publishing Company','publish_address' => '' ),
            array('id' => '313','publish_name' => ' Churchill Livingstone','publish_address' => 'London' ),
            array('id' => '317','publish_name' => 'Brunner/ Mazel','publish_address' => 'New York' ),
            array('id' => '318','publish_name' => ' Broadman Press','publish_address' => '' ),
            array('id' => '319','publish_name' => ' Philadelphia-The Westminster press','publish_address' => '' ),
            array('id' => '320','publish_name' => ' د. مدحت أديب','publish_address' => '5 شارع عمر بكير - مصر الجديدة - القاهرة' ),
            array('id' => '322','publish_name' => ' دار الفاروق للإستثمارات الثقافية','publish_address' => '12 ش الدقي - منزل كوبرى الدقي - إتجاه الجامعة - الجيزة - مصر' ),
            array('id' => '324','publish_name' => ' المركز القومي للترجمة','publish_address' => 'ش الجبلاية بالأوبرا' ),
            array('id' => '326','publish_name' => ' منشورات المشعل','publish_address' => '' ),
            array('id' => '327','publish_name' => ' بيت مدارس الأحد','publish_address' => '70 ش روض الفرج' ),
            array('id' => '328','publish_name' => ' الكنيسة الأسقفية بمصر وشمال أفريقيا','publish_address' => '' ),
            array('id' => '329','publish_name' => ' فريق الحياة الأفضل','publish_address' => '' ),
            array('id' => '330','publish_name' => ' مكتبة الأسرة','publish_address' => '' ),
            array('id' => '331','publish_name' => ' ابراهيم وطفي','publish_address' => 'طرطوس- حصين البحر - سوريا' ),
            array('id' => '332','publish_name' => 'Perennial library','publish_address' => '' ),
            array('id' => '333','publish_name' => 'Touchstone Book','publish_address' => '' ),
            array('id' => '334','publish_name' => 'A premier Book','publish_address' => '' ),
            array('id' => '335','publish_name' => 'Word Books publisher','publish_address' => '' ),
            array('id' => '336','publish_name' => 'Vine Books','publish_address' => '' ),
            array('id' => '337','publish_name' => 'Oliver Nelson','publish_address' => '' ),
            array('id' => '338','publish_name' => 'Power Books','publish_address' => '' ),
            array('id' => '339','publish_name' => 'Harper Perennial','publish_address' => '' ),
            array('id' => '340','publish_name' => 'Lifejourney Books','publish_address' => '' ),
            array('id' => '341','publish_name' => 'Harper / Hazelden Book','publish_address' => '' ),
            array('id' => '342','publish_name' => 'Living Books','publish_address' => '' ),
            array('id' => '343','publish_name' => 'Pyranee Books','publish_address' => '' ),
            array('id' => '344','publish_name' => 'A Lion International Paperback','publish_address' => '' ),
            array('id' => '345','publish_name' => 'Fireside Book','publish_address' => ''  ),
            array('id' => '346','publish_name' => 'TOR','publish_address' => ''  ),
            array('id' => '347','publish_name' => 'Augsburg','publish_address' => ''  ),
            array('id' => '348','publish_name' => 'Blackwell Scientific Publications','publish_address' => ''  ),
            array('id' => '349','publish_name' => 'Crown Publishers,INC','publish_address' => ''  ),
            array('id' => '350','publish_name' => 'Multnomah Books','publish_address' => ''  ),
            array('id' => '351','publish_name' => 'Pickering Paperbacks','publish_address' => ''  ),
            array('id' => '352','publish_name' => 'Sanlife Ministries','publish_address' => ''  ),
            array('id' => '353','publish_name' => 'Continuum Publishing Campany','publish_address' => ''  ),
            array('id' => '354','publish_name' => 'Oliver- Nelson Books','publish_address' => ''  ),
            array('id' => '355','publish_name' => 'Baker Books','publish_address' => ''  ),
            array('id' => '356','publish_name' => 'The Banner of Truth trust','publish_address' => ''  ),
            array('id' => '357','publish_name' => 'Simon & Schster','publish_address' => ''  ),
            array('id' => '358','publish_name' => 'Windblown Media','publish_address' => ''  ),
            array('id' => '359','publish_name' => 'Routledge Classics','publish_address' => ''  ),
            array('id' => '360','publish_name' => 'Penguin Books','publish_address' => ''  ),
            array('id' => '361','publish_name' => 'Nelson Books','publish_address' => ''  ),
            array('id' => '362','publish_name' => 'Harrison House','publish_address' => ''  ),
            array('id' => '363','publish_name' => 'Multinomah Publishers','publish_address' => ''  ),
            array('id' => '364','publish_name' => 'Regal','publish_address' => ''  ),
            array('id' => '365','publish_name' => 'دار الآداب','publish_address' => 'بيروت' ),
            array('id' => '366','publish_name' => 'مطبوعات نظرة للمستقبل','publish_address' => ''  ),
            array('id' => '367','publish_name' => 'جورج حبيب بباوى','publish_address' => ''  ),
            array('id' => '368','publish_name' => 'وجيه يوسف','publish_address' => ''  ),
            array('id' => '369','publish_name' => 'دار الساقي','publish_address' => 'بناية تابت -ش امين منيمنة ( نزلة السارولا) الحمراء- ' ),
            array('id' => '370','publish_name' => 'دار الفكر الإنجيلي للترجمة والنشر و التوزيع','publish_address' => ''  ),
            array('id' => '371','publish_name' => 'مشير سمير','publish_address' => 'القاهرة'  ),
            array('id' => '372','publish_name' => 'دار العين للنشر','publish_address' => 'القاهرة' ),
            array('id' => '373','publish_name' => 'دار الهدى للنشر والتوزيع','publish_address' => 'المنيا - مصر' ),
            array('id' => '374','publish_name' => 'The American University in Cairo Press','publish_address' => 'Cairo - Egypt'  ),
            array('id' => '375','publish_name' => 'دار سعاد الصباح','publish_address' => 'ص.ب 13 المقطم'  ),
            array('id' => '376','publish_name' => 'مكتبة باناريون','publish_address' => '16 ش عمر بكير متفرع من احمد فؤاد -ميدان ساننت فاتيما'  ),
            array('id' => '377','publish_name' => 'مركز بيت الحياة','publish_address' => ''  ),
            array('id' => '378','publish_name' => 'الشركة المصرية العالمية للنشر-لونجمان','publish_address' => '10 أ ش حسين واصف -ميدان المساحة - الدقي-الجيزة'  ),
            array('id' => '379','publish_name' => 'دار العرب للبستانى','publish_address' => ''  ),
            array('id' => '380','publish_name' => 'دار البستاني للنشر والتوزيع','publish_address' => ' تمرة 29 ش الفجالة 11271القاهرة - مصر'  ),
            array('id' => '381','publish_name' => 'Vision House','publish_address' => 'p.o.Box3875-ventura,California93006'  ),
            array('id' => '382','publish_name' => 'William Morrow & Company,Inc','publish_address' => '1350 Avenue of the Americas,NY 10019'  ),
            array('id' => '383','publish_name' => 'Orbis Books','publish_address' => 'Maryknoll, New York 10545'  ),
            array('id' => '384','publish_name' => 'منشورات الجمل','publish_address' => 'ص.ب.: 5438- 113 بيروت - لبنان'  ),
            array('id' => '385','publish_name' => 'دار الرشاد','publish_address' => 'ش جواد حسني- القاهرة 14'  ),
            array('id' => '386','publish_name' => 'رابطة أدباء المهجر','publish_address' => 'القاهرة - رالي - نيويورك'  ),
            array('id' => '387','publish_name' => 'اتحاد الكتاب العرب','publish_address' => 'دمشق'  ),
            array('id' => '388','publish_name' => 'McClelland and Stewart Ltd','publish_address' => ''  ),
            array('id' => '389','publish_name' => 'Penguin Group ','publish_address' => '375 Hudson Street,New York10014'  ),
            array('id' => '390','publish_name' => 'دائرة المكتبة الوطنبة','publish_address' => 'الأردن'  ),
            array('id' => '391','publish_name' => 'دار النشر المصرية','publish_address' => ''  ),
            array('id' => '392','publish_name' => 'الدار المتحدة للنشر','publish_address' => '92 ش البطركية -لبنان'  ),
            array('id' => '393','publish_name' => 'دار التلاقي للكتاب','publish_address' => '54 ش شاهين- الجيزة'  ),
            array('id' => '394','publish_name' => 'المركز الثقافي العربي','publish_address' => '42 الشارع الملكي الأحباس(الدار البيضاء - المغرب'  ),
            array('id' => '395','publish_name' => 'دار المدى للثقافة والنشر','publish_address' => 'سورية - دمشق'  ),
            array('id' => '398','publish_name' => 'سطور الجديدة','publish_address' => '8,23 تقسيم الشيشيني بجوار الكوبرى الدائرى- كورنيش المعادى'  ),
            array('id' => '397','publish_name' => 'سما للنشر والتوزيع','publish_address' => '29 ش الرشيدى- متفرع من القصر العيني - القاهرة'  ),
            array('id' => '399','publish_name' => 'مركز المطبوعات','publish_address' => 'ص.ب.5039 - بيروت'  ),
            array('id' => '400','publish_name' => 'W.M. B. Eerdmans Publishing CO.','publish_address' => ''  ),
            array('id' => '401','publish_name' => 'A.J.Holman Company','publish_address' => 'Philadelphia'  ),
            array('id' => '402','publish_name' => 'Kenyons Gospel Publishing Society,Inc.','publish_address' => 'P.o.Box 973,Lynnwood ,washington 98036'  ),
            array('id' => '403','publish_name' => 'Shepherd\'sHouse.Inc.','publish_address' => 'P.O.Box 40096 pasadena,CA91114'  ),
            array('id' => '404','publish_name' => 'World wide Publications','publish_address' => '1313 Hennepin Avenue Minneapolis,Minnesota 55403'  ),
            array('id' => '405','publish_name' => 'Canon Press','publish_address' => 'Washington,D.C.'  ),
            array('id' => '406','publish_name' => 'Unknown','publish_address' => ''  ),
            array('id' => '407','publish_name' => 'Presbyterian and Reformed Publishing Co. ','publish_address' => ''  ),
            array('id' => '408','publish_name' => 'Grace and Glory','publish_address' => '2515 Harrison Street Kansas City, Mo.'  ),
            array('id' => '409','publish_name' => 'الحياة','publish_address' => ''  ),
            array('id' => '410','publish_name' => 'Scripture Union ','publish_address' => '130 City road, London EC1v 2NJ'  ),
            array('id' => '411','publish_name' => 'الجمعية الأسقفية ببولاق مصر','publish_address' => ''  ),
            array('id' => '412','publish_name' => 'دار الكتاب المقدس','publish_address' => '1 ش الدكتور علي فهمي الزناتي -مصرالجديدة'  ),
            array('id' => '413','publish_name' => 'دار مجلة مرقس','publish_address' => '28 ش شبرا - القاهرة'  ),
            array('id' => '414','publish_name' => 'دار الأخوة للنشر','publish_address' => ''  ),
            array('id' => '415','publish_name' => 'دار الشرق والغرب','publish_address' => 'القاهرة'  ),
            array('id' => '416','publish_name' => 'هيئة الخدمة الروحية وتدريب القادة','publish_address' => 'ص.ب.4 سراى القبة - القاهرة'  ),
            array('id' => '417','publish_name' => 'North central Regional Extension Publications ','publish_address' => 'number\'s 36.1/ 36.11'  ),
            array('id' => '418','publish_name' => 'A Division of Standard Publishing','publish_address' => 'Cincinnati,Ohio 45231'  ),
            array('id' => '419','publish_name' => 'Edward Fudge publishing','publish_address' => '4 sandra lane.Athens.alabama35611' ),
            array('id' => '420','publish_name' => 'lockman Foundation','publish_address' => ''  ),
            array('id' => '421','publish_name' => 'College press publishing company,Joplin,Missouri','publish_address' => ''  ),
            array('id' => '422','publish_name' => 'Gospel light publishing company ','publish_address' => 'Delight,Arkansas' ),
            array('id' => '423','publish_name' => 'The religious Tract society','publish_address' => '4 Bouverie street and 65 Sr.paul\'s churchyard E.C.'  ),
            array('id' => '424','publish_name' => 'Oliphants Marshall,morgan&scott','publish_address' => '116 Baker Street london wim 2bb'  ),
            array('id' => '425','publish_name' => 'J.c.b.Mohr (Paul Siebeck)Tubingen','publish_address' => ''  ),
            array('id' => '426','publish_name' => 'مجمع اللغة العربية','publish_address' => ''  ),
            array('id' => '427','publish_name' => 'The British and foreign bible society','publish_address' => 'london'  ),
            array('id' => '428','publish_name' => 'American bible society','publish_address' => 'New york'  ),
            array('id' => '429','publish_name' => 'Logos International','publish_address' => '185,northavenue plainfield,new jersey'  ),
            array('id' => '430','publish_name' => 'مركز دراسات الأباء','publish_address' => '8 ش اسماعيل الفلكي - مصر الجديدة'  ),
            array('id' => '431','publish_name' => 'الدار للنشر و التوزيع','publish_address' => '' ),
            array('id' => '432','publish_name' => 'مكتبة التراث الأسلامي','publish_address' => '8 ش الجمهورية - عابدين'  ),
            array('id' => '433','publish_name' => 'منشورات دار الآداب','publish_address' => 'بيروت'  ),
            array('id' => '434','publish_name' => 'ورد للطباعة والنشر والتوزيع','publish_address' => 'سوريا -دمشق'  ),
            array('id' => '435','publish_name' => 'المؤسسة العربية للدراسات والنشر','publish_address' => 'بناية برج الكارلتون- ساقية الخنزير-بيروت '  ),
            array('id' => '436','publish_name' => 'منشورات عديدات','publish_address' => 'بيروت - باريس'  ),
            array('id' => '437','publish_name' => 'الهيئة التدريسية في جامعة جلوبال ','publish_address' => '1211 SouthGlenstone Avenue Springfield,missouri 65804-USA'  ),
            array('id' => '438','publish_name' => 'المجلس القومي للطفولة والأمومة','publish_address' => 'القاهرة'  ),
            array('id' => '439','publish_name' => 'سعيد مرقص إبراهيم','publish_address' => ''  ),
            array('id' => '440','publish_name' => 'Kegan Paul,Trench,Trubner &co,','publish_address' => ''  ),
            array('id' => '441','publish_name' => 'Africa Christian press','publish_address' => ''  ),
            array('id' => '442','publish_name' => 'Insight for living','publish_address' => 'post office Box 4444 Fullerton,California 92634'  ),
            array('id' => '443','publish_name' => 'w Publishing Group','publish_address' => ''  ),
            array('id' => '444','publish_name' => 'Warner Books','publish_address' => ''  ),
            array('id' => '445','publish_name' => 'خدمة الحياة','publish_address' => ''  ),
            array('id' => '446','publish_name' => 'مركز دراسات الأباء','publish_address' => ''  ),
            array('id' => '447','publish_name' => 'الدار المصرية للطباعة والنشر والتوزيع','publish_address' => '23 ش سامي بالمالية'  ),
            array('id' => '448','publish_name' => 'Harcourt Brace College Publishers','publish_address' => ''  ),
            array('id' => '449','publish_name' => 'Grason','publish_address' => ''  ),
            array('id' => '450','publish_name' => 'Longman group limited','publish_address' => ''  ),
            array('id' => '451','publish_name' => 'Faber and Faber','publish_address' => 'London'  ),
            array('id' => '452','publish_name' => 'Marshall Pickering','publish_address' => '77-85 fulham palace road,London w6 8jb'  ),
            array('id' => '453','publish_name' => 'Chrism Books ','publish_address' => ''  ),
            array('id' => '454','publish_name' => 'Lion publishing','publish_address' => ''  ),
            array('id' => '455','publish_name' => 'عماد ميشيل','publish_address' => ''  ),
            array('id' => '456','publish_name' => 'مركز الأهرام للنشر والترجمة والتوزيع','publish_address' => ''  ),
            array('id' => '457','publish_name' => 'دار دون للنشر و التوزيع','publish_address' => '1 ش السعادة -نصوح- الزيتون - القاهرة'  ),
            array('id' => '458','publish_name' => 'دار الكتاب العربي ','publish_address' => 'الجميلية -أمام مسرح نقابة الفنانين - حلب'  ),
            array('id' => '459','publish_name' => 'هالة قفؤاد','publish_address' => ''  ),
            array('id' => '460','publish_name' => 'ق.جورجي أسعد','publish_address' => ''  ),
            array('id' => '461','publish_name' => 'دال للنشر والتوزيع','publish_address' => 'سوريا-دمشق-ص ب 29170'  ),
            array('id' => '462','publish_name' => 'دار المني','publish_address' => 'Box127-18205 Djursholm -Sweden'  ),
            array('id' => '463','publish_name' => 'interlink ltd.co.','publish_address' => 'hatboyu cad no32/9 pendik-istanbul-turkey'  ),
            array('id' => '464','publish_name' => 'كلمات عربية للترجمة والنشر','publish_address' => 'ص.ب. 50 - مدينة نصر -11768 - القاهرة'  ),
            array('id' => '465','publish_name' => 'preceptaustin.org','publish_address' => ''  ),
            array('id' => '466','publish_name' => 'Bible lessons international','publish_address' => 'P.o. Box 1289 Marshall,Tx 75671.USA'  ),
            array('id' => '467','publish_name' => 'Barnes and Nobel books','publish_address' => 'new york'  ),
            array('id' => '468','publish_name' => 'دار ميريت','publish_address' => '6 ب شارع قصر النيل - القاهرة' ),
            array('id' => '469','publish_name' => 'زوى','publish_address' => '' ),
            array('id' => '470','publish_name' => 'سامي فوزى','publish_address' => '' ),
            array('id' => '471','publish_name' => 'Vintage books- A division of Random House ,inc.','publish_address' => 'new york' ),
            array('id' => '472','publish_name' => 'مركز مورغان للنشر والأعلام ','publish_address' => 'بيروت- لبنان'  ),
            array('id' => '473','publish_name' => 'كنيسة الشهيد العظيم مارجرجس','publish_address' => 'سبورتمج'  ),
            array('id' => '474','publish_name' => 'مركز الحياه الأفضل لمكافحة الإدمان والأيدز','publish_address' => ''  ),
            array('id' => '475','publish_name' => 'هفن للترجمة والنشر والبرمجبات ','publish_address' => '5 شارع احمد طلعت -المبتديان'  ),
            array('id' => '476','publish_name' => 'ماستر ميديا','publish_address' => 'عمارة برج الجزائر- 23 طريق مصر حلوان الزراعي-المعادى'  ),
            array('id' => '478','publish_name' => 'حلمي مراد','publish_address' => 'عمارة الجندول ش 26 يوليو'  ),
            array('id' => '479','publish_name' => 'لافينيا','publish_address' => '' ),
            array('id' => '480','publish_name' => 'Beacon press','publish_address' => 'Boston' ),
            array('id' => '481','publish_name' => 'Christian Books publishing house','publish_address' => 'Box 959 Gardiner maine 04345'  ),
            array('id' => '482','publish_name' => 'Pinon Press','publish_address' => 'P.o.Box 35007 Colorado Springs, Colorado 80935'  ),
            array('id' => '483','publish_name' => 'الشركة المتحدة للتوزيع','publish_address' => 'سوريا' ),
            array('id' => '484','publish_name' => 'د. صموئيل رزفي  إبراهيم','publish_address' => ''  ),
            array('id' => '485','publish_name' => 'منشأة المعارف','publish_address' => 'الأسكندرية'  ),
            array('id' => '486','publish_name' => 'دير سيدة الكرمل','publish_address' => 'الحازمية ص.ب.285'  ),
            array('id' => '487','publish_name' => 'دار كنعان للدراسات والنشر والخدمات الإعلامية','publish_address' => 'دمشق'  ),
            array('id' => '488','publish_name' => 'دار معد للنشر والتوزيع','publish_address' => 'سوريا - دمشق'  ),
            array('id' => '489','publish_name' => 'Tabgha foundation ','publish_address' => 'Minneapolis , Minnesota'  ),
            array('id' => '490','publish_name' => 'مطبوعات الحياة المنتصرة','publish_address' => ''  ),
            array('id' => '491','publish_name' => 'West minster- John Knox press','publish_address' => 'Kintucky'  ),
            array('id' => '492','publish_name' => 'دار الفارابي','publish_address' => 'بيروت - لبنان'  ),
            array('id' => '493','publish_name' => 'دير السيدة العذراء - برموس','publish_address' => ''  ),
            array('id' => '494','publish_name' => 'دار النهار','publish_address' => 'بيروت'  ),
            array('id' => '495','publish_name' => 'شركة الأمل للطباعة والنشر','publish_address' => 'القاهرة'  ),
            array('id' => '496','publish_name' => 'The arab association of philosophical societies','publish_address' => ''  ),
            array('id' => '497','publish_name' => 'Arab Association of Philosophical Societies','publish_address' => ''  ),
            array('id' => '498','publish_name' => 'المكتبة الثقافية - منشورات تضامن المرأة العربية ','publish_address' => '4الف شارع ظريف سعد - القصر العيني'  ),
            array('id' => '499','publish_name' => 'المكتبة الثقافية - منشورات تضامن المرأة العربية ','publish_address' => '4الف شارع ظريف سعد - القصر العيني'  ),
            array('id' => '500','publish_name' => 'دار اللياس العصرية للطباعة والنشر','publish_address' => '1 شارع الروم الكاثوليك - الظاهر - القاهرة'  ),
            array('id' => '501','publish_name' => 'Manar Book Shop','publish_address' => 'القاهرة'  ),
            array('id' => '503','publish_name' => 'مؤسسة القديس أنطونيوس','publish_address' => 'المركز الأرثوذكسي للدراسات الآبائية'  ),
            array('id' => '504','publish_name' => 'بيت التكريس لخدمة الكرازة','publish_address' => '12 شارع الخندق - حدائق القبة - القاهرة'  ),
            array('id' => '505','publish_name' => 'دير القديس الأنبا مقار','publish_address' => ''  ),
            array('id' => '506','publish_name' => 'كنيسة قصر الدوبارة','publish_address' => 'القاهرة - مصر'  ),
            array('id' => '507','publish_name' => 'خدمة ذهن جديد','publish_address' => 'مصر'  ),
            array('id' => '508','publish_name' => 'georgeibrahim2257@yahoo.com','publish_address' => '' ),
            array('id' => '509','publish_name' => 'رسالة القديسة تريزا ليسوع الطفل ','publish_address' => 'شبرا - مصر'  ),
            array('id' => '510','publish_name' => 'مكتبة دار نداء الرجاء ','publish_address' => 'ص.ب.985 -حمص - سوريا'  ),
            array('id' => '511','publish_name' => 'العربي للنشر والتوزيع','publish_address' => '60 ش القصر العيني'  ),
            array('id' => '512','publish_name' => 'مركز المحروسة','publish_address' => '4 شارع 9 ب المعادى'  ),
            array('id' => '513','publish_name' => 'مكتبة أنجيلوس','publish_address' => ''  ),
            array('id' => '514','publish_name' => 'مدرسة اللاهوت المعمدانية','publish_address' => 'لبنان'  ),
            array('id' => '515','publish_name' => 'دار الوراق للنشر المحدودة','publish_address' => 'لندن'  ),
            array('id' => '516','publish_name' => 'معهد المراسلة الدولي ','publish_address' => 'بروكسل'  ),
            array('id' => '517','publish_name' => 'المركز الأرثوزكسي للدراسات الأبائية','publish_address' => ''  ),
            array('id' => '518','publish_name' => 'مدرسة اللأهوت المعمدانية العربية + دار منهل الحياة','publish_address' => ''  ),
            array('id' => '519','publish_name' => 'Image Book','publish_address' => 'New York'  ),
            array('id' => '520','publish_name' => 'دار عويدات للنشر والطباعة','publish_address' => 'ص.ب. 628 بيروت - لبنان'  ),
            array('id' => '521','publish_name' => 'أجابيه للنشر','publish_address' => '6 ب شارع عبد اللطيف المكباتي - سانت فاتيما - القاهرة'  ),
            array('id' => '522','publish_name' => 'دار قابس','publish_address' => 'ص.ب.274 لبنان بيروت  ساحة الغبيري'  ),
            array('id' => '523','publish_name' => 'دار التكوين ','publish_address' => 'ص.ب.  11418دمشق - سوريا'  ),
            array('id' => '524','publish_name' => 'المنظمة العربية للترجمة','publish_address' => 'بناية بيت النهضة -شارع البصرة-بيروت ص.ب. 113- 5996'  ),
            array('id' => '525','publish_name' => 'من أجل العائلة','publish_address' => ''  ),
            array('id' => '526','publish_name' => 'مكتبة مارمرقس بالأنبا رويس','publish_address' => 'العباسية - القاهرة - مصر'  ),
            array('id' => '527','publish_name' => 'منشورات وزارة الثقافة والأرشاد القومي','publish_address' => 'دمشق'  ),
            array('id' => '528','publish_name' => 'شباب بوكس للنشر والتوزيع','publish_address' => 'القاهرة'  ),
            array('id' => '529','publish_name' => 'Nav press bringing of life','publish_address' => 'P.O.Box 35001.Colrado Springs. Colorado 80935'  ),
            array('id' => '531','publish_name' => 'New Harbinger Publications,Inc.','publish_address' => '5674 Stattuck Avenue Oakland,CA 94609'  ),
            array('id' => '532','publish_name' => 'مطبعة الدلتا','publish_address' => '24 شارع الدلتا - سبورتنج - الأسكندرية'  ),
            array('id' => '533','publish_name' => 'Sahara International school','publish_address' => '5 Seif Al Din Mohrany St. Ramses Sq. Cairo Egypt'  ),
            array('id' => '534','publish_name' => 'كنيسة السيدة العذراء - محرم بك - الأسكندرية','publish_address' => ''  ),
            array('id' => '535','publish_name' => 'Pickering & Inglis LTD.','publish_address' => 'London'  ),

            array('id' => '536','publish_name' => 'الخدمة العربية المسيحية','publish_address' => ''),
            array('id' => '537','publish_name' => 'دار صفصافة للنشر','publish_address' => '5 شارع المسجد الاقصي - الجيزة'),
            array('id' => '538','publish_name' => 'المركز الأثوزكسي للدراسات الآبائية','publish_address' => 'القاهرة'),
            array('id' => '539','publish_name' => 'Conciliar press','publish_address' => 'P.O.BOX 76 Ben Lomond,California'),
            array('id' => '540','publish_name' => 'جذور للترجمة والنشر','publish_address' => ''),
            array('id' => '541','publish_name' => 'الأهالي للطباعة والنشر والتوزيع','publish_address' => 'دمشق ص.ب 9223'),
            array('id' => '542','publish_name' => 'دار الكرمة الحقيقية للنشر والترجمة والتوزيع','publish_address' => 'ميدان سفير - مصر الجديدة'),
            array('id' => '543','publish_name' => 'الحرية للنشر والتوزيع','publish_address' => '3 ميدان عرابي - القاهرة'),
            array('id' => '544','publish_name' => 'مركز جامعة القاهرة للغات والترجمة','publish_address' => ''),
            array('id' => '545','publish_name' => 'جمعية الكتاب المقدس ','publish_address' => 'بيروت - لبنان'),
            array('id' => '546','publish_name' => 'مدرسة الأسكندرية','publish_address' => '3 شارع الفاطميين-متفرع من عمر ابن الخطاب - ميدان الإسماعيلية - مصر الجديدة'),
            array('id' => '547','publish_name' => 'آدم كلارك','publish_address' => ''),
            array('id' => '549','publish_name' => 'الناشر العربي','publish_address' => ''),
            array('id' => '550','publish_name' => 'كنيسة مارمرقس - مصر الجديدة','publish_address' => ''),
            array('id' => '551','publish_name' => 'منشورات الإختلاف- دار أوما- منشورات ضفاف','publish_address' => 'الجزائر- العراق- الرياض- بيروت'),
            array('id' => '553','publish_name' => 'عربية للطباعة والنشر','publish_address' => '7-10 شارع السلام ارض اللواء - المهندسين'),
            array('id' => '554','publish_name' => 'العبيكان','publish_address' => 'ش العليا العليا العام-جنوب برج المملكة - عمارة الموسي للمكاتب- السعودية'),
            array('id' => '555','publish_name' => 'دار العلم العربي','publish_address' => '2 شارع إمتداد رمسيس 1 - مدينة نصر - القاهرة'),
            array('id' => '556','publish_name' => 'د. سعيد حكيم يعقوب','publish_address' => ''),
            array('id' => '557','publish_name' => 'Christian Classics Ethereal Library','publish_address' => ''),
            array('id' => '558','publish_name' => 'دار يوسف كمال للطباعة','publish_address' => 'القاهرة -مصر'),
            array('id' => '559','publish_name' => 'جداول للنشر والترجمة والتوزيع','publish_address' => 'الحمرا ء- شارع الكويت- بناية البركة - الطابق الأول- شوران - بيروت - لبنان'),
            array('id' => '560','publish_name' => 'الدار العالمية للكتب والنشر','publish_address' => '15 شارع الفاروق عمر بن الخطاب - الطالبية -فيصل - الجيزة - مصر'),
            array('id' => '561','publish_name' => 'christion Internationl copy center','publish_address' => 'USA'),
            array('id' => '562','publish_name' => 'Alfred A. Knopf','publish_address' => ''),
            array('id' => '563','publish_name' => 'مؤسسة هنداوي للتعليم والثقافة','publish_address' => '54 عمارات الفتح - حي السفارات - مدينة نصر - القاهرة'),
            array('id' => '564','publish_name' => 'دار المعارف الحكيمة','publish_address' => 'حارة حريك - الشارع العريض- سنتر صولي - ط2 شمالي'),
            array('id' => '565','publish_name' => 'دار خان','publish_address' => 'رمسيس- القاهرة'),
            array('id' => '566','publish_name' => 'دار نهضة مصر','publish_address' => '21 ش احمد عرابي - المهندسين - الجيزة'),
            array('id' => '567','publish_name' => 'دار الثقافة الجديدة','publish_address' => '32 شارع صبري أبو علم - باب اللوق- القاهرة'),
            array('id' => '568','publish_name' => 'Tikhon\'s Monastery press','publish_address' => '175 St, Tikhon road'),
            array('id' => '569','publish_name' => 'الكرمة للنشر والتوزيع','publish_address' => 'القاهرة'),
            array('id' => '570','publish_name' => 'دار أثر للنشر والتوزيع','publish_address' => 'السعودية - الدمام'),
            array('id' => '571','publish_name' => 'تعاونية النور الأرثوذكسية','publish_address' => 'بيروت - لبنان'),
            array('id' => '572','publish_name' => 'روافد للنشر والتوزيع','publish_address' => 'القاهرة'),
            array('id' => '573','publish_name' => 'الأكويني - دير الدومنيكان','publish_address' => '1 ش مصنع الطرابيش - العباسية القاهرة'),
            array('id' => '574','publish_name' => 'دلتا للخدمات','publish_address' => '01221718087'),
            array('id' => '575','publish_name' => 'الأهلية للنشر والتوزيع','publish_address' => 'الأردن - عمان- وسط البلد بناية 12 وبناية 34'),
            array('id' => '576','publish_name' => 'دار الحرف العربي للنشر والتوزيع','publish_address' => 'زقاق البلاط - بناية فخر الدين - بيروت - لبنان'),
            array('id' => '577','publish_name' => 'مركز زايد للنشر الألكتروني ','publish_address' => '119- شارع الكورنيش'),
            array('id' => '578','publish_name' => 'آفاق الأولي','publish_address' => 'القاهرة'),
            array('id' => '579','publish_name' => 'د. محمد احمد غالي','publish_address' => ''),
            array('id' => '580','publish_name' => 'الميزان للنشر والتوزيع','publish_address' => ''),
            array('id' => '581','publish_name' => 'توبيا للنشر والتوزيع','publish_address' => '213 ش عبد الوهاب عبد اللطيف كوبري القبة'),
            array('id' => '582','publish_name' => 'دار الربيع العربي ','publish_address' => 'القاهرة - مصر'),
            array('id' => '583','publish_name' => 'دار الفرقد','publish_address' => 'سورية - دمشق'),
            array('id' => '584','publish_name' => 'خدمة credologos','publish_address' => ''),
            array('id' => '586','publish_name' => 'دار تويقة للنشر والتوزيع','publish_address' => '7 ش ابو العطا - فيصل - الجيزة'),

            array('id' => '587','publish_name' => ' آفاق للنشر و التوزيع','publish_address' => 'ش بسيوني - طلعت حرب'),
  array('id' => '588','publish_name' => 'دار تويا للنشر والتوزيع','publish_address' => '35 ش النصر - المعادي'),
  array('id' => '589','publish_name' => 'خدمة لؤلؤة - قصر الدوبارة','publish_address' => '7 ش ريحان - جاردن سيتي'),
  array('id' => '590','publish_name' => 'برنامج الحياة ','publish_address' => '7 ش ريحان - جاردن سيتي'),
  array('id' => '591','publish_name' => 'دار الشئون الثقافية العامة','publish_address' => 'بغداد - العراق'),
  array('id' => '592','publish_name' => 'أقلام عربية للنشر والتوزيع','publish_address' => '1 ش كريم الدولة - امام جروبي - طلعت حرب - القاهرة'),
  array('id' => '593','publish_name' => 'مركز بالعقل نبدأ للدراسات والأبحاث','publish_address' => ' ش22خيرت من ميدان لاظوغلي - السيدة زينب - القاهرة'),
  array('id' => '594','publish_name' => 'منشورات البندقية ','publish_address' => 'ش 20 جواد حسني من ش قصر النيل - وسط البلد- القاهرة'),
  array('id' => '595','publish_name' => 'صفصافة للنشر والتوزيع','publish_address' => 'ش 5 المسجد الأقصي من ش المنشية - الجيزة'),
  array('id' => '596','publish_name' => 'مركز براهين للأبحاث و الدراسات','publish_address' => ''),
  array('id' => '597','publish_name' => 'خدمة الحق يحرركم','publish_address' => 'tsf.ministry@gmail.com'),
  array('id' => '598','publish_name' => 'معهد عمواس للكتاب المقدس','publish_address' => ''),
  array('id' => '599','publish_name' => 'دير القديس العظيم الأنبا أنطونيوس','publish_address' => 'البحر الأحمر - مصر'),
  array('id' => '600','publish_name' => 'Piatkus','publish_address' => 'sovictoria embaukment-london'),
  array('id' => '601','publish_name' => 'tsf.ministry@gmail.com','publish_address' => ''),
  array('id' => '602','publish_name' => 'الحوار للنشر والتوزيع','publish_address' => 'اللاذقية - سوريا'),
  array('id' => '605','publish_name' => 'مؤسسة حورس الدولية','publish_address' => '144 ش طيبة - سبورتنج - الأسكندرية'),
  array('id' => '606','publish_name' => 'دار نور المعارف للنشر و التوزيع','publish_address' => ''),
  array('id' => '607','publish_name' => 'بليدج كوميونكيشنز','publish_address' => ''),
  array('id' => '608','publish_name' => 'تيست ٢','publish_address' => 'تيست ٢'),
  array('id' => '610','publish_name' => 'الكنيسة المعمداني ب دراو','publish_address' => ''),
  array('id' => '611','publish_name' => 'اشرف عزمي','publish_address' => ''),
  array('id' => '612','publish_name' => 'The Guildford press','publish_address' => '72 springstreet- NewYork'),
  array('id' => '613','publish_name' => 'The Norton series','publish_address' => 'New York'),
  array('id' => '614','publish_name' => 'Lyla Swafford','publish_address' => 'USA'),
  array('id' => '615','publish_name' => 'H.L.Heijkoop','publish_address' => '58 BlJham ster-street.winschoteul/netherlands'),
  array('id' => '616','publish_name' => 'مكتبة النافذة','publish_address' => '1 ش حسن دياب -برج مكة 3 ميدان الساعة - الجيزة'),
  array('id' => '617','publish_name' => 'منشورات جمعية الطب النفسي التطوعي','publish_address' => ''),
  array('id' => '618','publish_name' => 'دار رسالتنا للنشر والتوزيع','publish_address' => ''),
  array('id' => '619','publish_name' => 'مشروع كلمة ','publish_address' => 'هيئة أبو ظبي للسياحة والثقافة'),
  array('id' => '620','publish_name' => 'منشورات الرمل','publish_address' => '24 نهج سعيد أبو بكر 1001 تونس'),
  array('id' => '621','publish_name' => 'دار الكاتب للطباعة والنشر والتوزيع','publish_address' => ''),
  array('id' => '622','publish_name' => 'Rhkhawy','publish_address' => ''),
  array('id' => '623','publish_name' => 'winged Heart Press','publish_address' => 'Kalamazoo'),
  array('id' => '624','publish_name' => 'Jossy-Bass Inc. Publishers','publish_address' => '350 San some Street San Francisco,LA'),
  array('id' => '625','publish_name' => 'Public Affairs','publish_address' => '250 west 57th st. 15th fioor, NY'),
  array('id' => '626','publish_name' => 'منشورات دير سيده البشاره','publish_address' => 'حلب سوريا'),
  array('id' => '627','publish_name' => 'رسالتنا للنشر و التوزيع','publish_address' => ''),
  array('id' => '628','publish_name' => 'عالم الأدب للترجمة والنشر ','publish_address' => 'مصر'),
  array('id' => '629','publish_name' => 'كلام الحياه الأبدية','publish_address' => ''),
  array('id' => '630','publish_name' => 'لؤلؤة','publish_address' => ''),
  array('id' => '631','publish_name' => 'هيئة أبو ظبي للثقافة والتراث','publish_address' => 'أبو ظبي - الإمارات'),
  array('id' => '632','publish_name' => 'دار الوليد للدراسات والنشر والترجمة','publish_address' => '52 ش عبد الخالق ثروت - القاهرة'),
  array('id' => '633','publish_name' => 'د.ك.موريس يوسف','publish_address' => ''),
  array('id' => '634','publish_name' => 'The Free Frees','publish_address' => '1230 Avenue of the Americans - New York .NY 10020'),
  array('id' => '635','publish_name' => 'Who Library Cataloguing - in - Publication Data','publish_address' => 'Swizerland,27Geneva 1211,Arenne appia 20'),
  array('id' => '636','publish_name' => 'المكتب الأقليمي لمنظمة الصحة العالمية للشرق الأوسط','publish_address' => 'ص.ب.7608 مدينة نصر - القاهرة 11371 - مصر'),
  array('id' => '637','publish_name' => 'كتب عربية','publish_address' => ''),
  array('id' => '638','publish_name' => 'Gotham Book , a divison of Penguin group','publish_address' => '375 Hudson st,new york 10014, USA'),
  array('id' => '639','publish_name' => 'مسرح عشتار','publish_address' => ''),
  array('id' => '640','publish_name' => 'المركز القومي للترجمة بالتعاون مع دار العين للنشر ','publish_address' => ''),
  array('id' => '641','publish_name' => 'مجاز للترجمة والنشر','publish_address' => '64 ش سليم الأول - الزيتون - القاهرة'),
  array('id' => '642','publish_name' => 'North Atlantic Books - Ergos Institute Press','publish_address' => 'Berkeley California p.o.Box 110 Lyons,Colrado 80540'),
  array('id' => '643','publish_name' => 'مركز الإصلاح للتدريب','publish_address' => ''),
  array('id' => '644','publish_name' => 'الفنية للطباعة والنشر','publish_address' => '48 ش جودة رأس التيين - الأسكندرية'),
  array('id' => '646','publish_name' => 'مؤسسة رسلان للطباعة والنشر','publish_address' => 'دمشق - جرمانا الاس الشرقي'),
  array('id' => '647','publish_name' => 'دار وائل للطباعة والنشر ','publish_address' => 'ش الجمعية العلمية - الأردن - عمان - ص.ب.1746'),
  array('id' => '648','publish_name' => 'الأمل - مصر','publish_address' => ''),
  array('id' => '649','publish_name' => 'The Dougy Center','publish_address' => 'Portland - Oregon  97286'),
  array('id' => '650','publish_name' => 'Memory Books for children International','publish_address' => 'Gresham - Oregon -097030 '),
  array('id' => '651','publish_name' => 'شركه بليدج كوميونيكشن','publish_address' => ''),
  array('id' => '652','publish_name' => 'دار البشائر للطباعه والنشر ولبتوريع','publish_address' => 'شارع 29 آيار -جادة كرجيب حداد - دمشق'),
  array('id' => '653','publish_name' => 'رؤية للنشر والتوزيع','publish_address' => '6 ش البطل أحمد عبد العزيز - عابدين - القاهره'),
  array('id' => '654','publish_name' => 'منشورات الربيع','publish_address' => 'القاهره'),
  array('id' => '655','publish_name' => 'المكتبه االبولسية','publish_address' => 'ص.ب. 125 جونيه - لبنان'),
  array('id' => '656','publish_name' => 'الدار الذهبيه للطبع والنشر والتوزيع','publish_address' => '15 ش الجمهوريه - عابدين'),
  array('id' => '657','publish_name' => 'تكوين للدراسات والأبحاث','publish_address' => ''),
  array('id' => '658','publish_name' => 'دار الأكويني','publish_address' => 'دير الدومينكان - 1شارع مصتع الطرابيش- العباسيه'),
  array('id' => '659','publish_name' => 'Atria Paperback & Beyond Words','publish_address' => 'عين التين ش المفتي توفيق خالد -بنايه الريم - لبنان'),
  array('id' => '660','publish_name' => 'دار الرافدين ','publish_address' => 'لبنان - بيروت'),
  array('id' => '661','publish_name' => 'الرحبة للنشر والتوزيع','publish_address' => 'دمشق - سوريا'),
  array('id' => '662','publish_name' => 'دير القديسه العفيفة دميانة','publish_address' => 'براري بلقاس'),
  array('id' => '663','publish_name' => 'أكادمية شبابيك','publish_address' => ''),
  array('id' => '664','publish_name' => 'إيتراك للطباعة و النشر و التوزيع','publish_address' => ''),
  array('id' => '665','publish_name' => 'دار العالية للنشر والخدمات التعليمية','publish_address' => ''),
  array('id' => '666','publish_name' => 'مكتبة الشقري ','publish_address' => 'السعودية - طريق الملك فهد - شمال برج المملكة -مجمع البستان التجاري -مكتب 34'),
  array('id' => '667','publish_name' => 'مؤسسة هنداوي ','publish_address' => '3 هاي ستريت وندسور - المملكة المتجدة'),
  array('id' => '668','publish_name' => 'Random House Books','publish_address' => 'www.randomhouse.co.uk/office.htm'),
  array('id' => '669','publish_name' => 'بيت الياسمين للنشر والتوزيع','publish_address' => '71ب حرائق الأهرام - البوابخ الأولي '),
  array('id' => '670','publish_name' => 'karnac classics','publish_address' => 'H.Karnac(book)Ltd.o pembroke Buildings London NW 106re '),
  array('id' => '671','publish_name' => 'إيجلز جروب - د, سامي فوزي','publish_address' => ''),
  array('id' => '672','publish_name' => 'Karnac Classics','publish_address' => 'H,Karnac (books) Ltd, London Nw 106RE'),
  array('id' => '673','publish_name' => 'IST Training','publish_address' => ''),
  array('id' => '674','publish_name' => 'Icon Books','publish_address' => '0mnibus Business center 39-41north road,Londen N79DP'),
  array('id' => '675','publish_name' => 'مركز المحروسه للنشر و الخدمات الصحفيه و المعلومات ','publish_address' => 'قطعه رقم 7399 ش 98 من ش 9 - المقطم'),
  array('id' => '676','publish_name' => 'الرواق للنشر و التوزيع','publish_address' => '186 غمارات امتداد رمسيس 2 امام ارض المعارض-مدينه نصر'),
  array('id' => '677','publish_name' => 'مطبعة : سان مارك','publish_address' => ''),
  array('id' => '678','publish_name' => 'عصير الكتب للنشر والتوزيع','publish_address' => 'P.bookjuice@yahoo.com'),
  array('id' => '679','publish_name' => 'دار روابط للنشر و تقنية المعلومات','publish_address' => '19 ش حسن أفلاطون بجوار مستشفي عبد القادر فهمي - ارض الجولف - مصر الجديده'),
  array('id' => '680','publish_name' => 'بسطرون للطباعه و النشر والتوزيع','publish_address' => '3 ش صفوت - محطة المطبعة شارع الملك فيصل - الجيزة'),
  array('id' => '682','publish_name' => 'إنسياير للنشر و التوزيع','publish_address' => ''),
  array('id' => '683','publish_name' => 'مؤسسة أخبار اليوم - قطاع الثقافة','publish_address' => ''),
  array('id' => '684','publish_name' => 'سينا للطباعة والنشر','publish_address' => '18 ش ضريح سعد - القصر العيني '),
  array('id' => '685','publish_name' => 'مطابع الهيئة المصرية','publish_address' => ''),
  array('id' => '686','publish_name' => 'مؤسسة سجل العرب','publish_address' => '26 ش شريف باشا - القاهره'),
  array('id' => '687','publish_name' => 'دار الكتاب الجامعي ','publish_address' => 'غزه - فلسطين'),
  array('id' => '688','publish_name' => 'المركز العربي للدراسات الأمنيةو التدريب بالرياض','publish_address' => 'الرياض'),
  array('id' => '689','publish_name' => 'المكتب العربي للمعارف','publish_address' => 'ش 26 حسين خضر من ش عبد العزيز فهمي -ميران هليوبليس مصر الجديدة - القاهرة'),
  array('id' => '690','publish_name' => 'صفحة 7 ','publish_address' => 'الجبيل - ش مشهور - السعوديه'),
  array('id' => '691','publish_name' => 'نابو للنشر و التوزيع','publish_address' => 'ص.ب. 5047 مكتب بريد الرشيد - بغداد - العراق'),
  array('id' => '692','publish_name' => 'سباركل للنشر','publish_address' => 'منشية البكري - مصر الجديدة'),
  array('id' => '693','publish_name' => 'ملهمون للنشر والتوزيع','publish_address' => ''),
  array('id' => '694','publish_name' => 'Meg Wilson','publish_address' => 'U.S.A.'),
  array('id' => '695','publish_name' => 'Kregel Publication','publish_address' => 'p.o.2607,Grand Rapids,MI49501'),
  array('id' => '696','publish_name' => 'Sounds true','publish_address' => ''),
  array('id' => '697','publish_name' => 'Dr.Louise Gaston','publish_address' => ''),
  array('id' => '698','publish_name' => 'الشبكة العربية للأبحاث و النشر ','publish_address' => '22ش عبد الخالق ثروت - وسط البلد القاهره مصر'),
  array('id' => '699','publish_name' => 'Biblica 1988','publish_address' => ''),
  array('id' => '700','publish_name' => 'كلية اللأهوت INSTE','publish_address' => '')


          );
          
    
    
        foreach($publishers as $publish){
            Publisher::create($publish);
        }
    }
}
