<?php

namespace Database\Seeders;

use App\Models\Translator;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TranslatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table((new \App\Models\Translator())->getTable())->truncate();
        
        $translators = array(
            array('id' => '1','translator_name' => '- Not translated/غير مترجم -'),
  array('id' => '2','translator_name' => 'د. سامي فوزي'),
  array('id' => '3','translator_name' => 'د. إيفا وهيب'),
  array('id' => '4','translator_name' => 'مشير سمير'),
  array('id' => '5','translator_name' => 'قسم الترجمة بدار الفاروق'),
  array('id' => '6','translator_name' => 'نشوى ماهر'),
  array('id' => '7','translator_name' => 'غير متاح'),
  array('id' => '8','translator_name' => 'غير معروف'),
  array('id' => '9','translator_name' => 'عبد الكريم احمد'),
  array('id' => '10','translator_name' => 'محمد بدر الدين خليل'),
  array('id' => '11','translator_name' => 'فؤاد حبيب'),
  array('id' => '12','translator_name' => 'ق. منيس عبد النور'),
  array('id' => '13','translator_name' => 'ق. رفعت فتحي'),
  array('id' => '14','translator_name' => 'ق. باقي صدقة'),
  array('id' => '15','translator_name' => 'د. ماريانا عبد الكريم كيرلس'),
  array('id' => '16','translator_name' => 'مينا مدحت- مارسيل مدحت'),
  array('id' => '17','translator_name' => 'د. مودى واصف عبد الملك'),
  array('id' => '18','translator_name' => 'سليم اسكندر حنا'),
  array('id' => '19','translator_name' => 'القمص مرقص داود'),
  array('id' => '20','translator_name' => 'ق. توفيق مشرقي دوس'),
  array('id' => '21','translator_name' => 'حسين مكي'),
  array('id' => '22','translator_name' => 'كمال زاخر لطيف'),
  array('id' => '23','translator_name' => 'صلاح عبد الصبور- وحيد النقاش'),
  array('id' => '24','translator_name' => 'محمد حسن أحمد غنيم'),
  array('id' => '25','translator_name' => ''),
  array('id' => '26','translator_name' => 'نهاد خياطة'),
  array('id' => '27','translator_name' => 'وجيه اسعد'),
  array('id' => '28','translator_name' => 'إدوارد وديع عبد المسيح'),
  array('id' => '29','translator_name' => 'صفاء الأعسر'),
  array('id' => '30','translator_name' => 'د. جرجس ميلاد'),
  array('id' => '31','translator_name' => 'مجاهد عبد المنعم مجاهد'),
  array('id' => '32','translator_name' => 'حنا يوسف'),
  array('id' => '33','translator_name' => 'ماهر نكلس نسيم'),
  array('id' => '34','translator_name' => 'أريج محمد غنيم'),
  array('id' => '35','translator_name' => 'ندى بريدى'),
  array('id' => '36','translator_name' => 'الأب سليم دكاش اليسوعي'),
  array('id' => '37','translator_name' => 'القمص تادرس يعقوب ملطي'),
  array('id' => '39','translator_name' => 'فاطمة ناعوت'),
  array('id' => '40','translator_name' => 'د. إيفيت صليب'),
  array('id' => '41','translator_name' => 'كلير بو ناصيف'),
  array('id' => '42','translator_name' => 'ميشال خورى'),
  array('id' => '43','translator_name' => 'حمد العيسي'),
  array('id' => '44','translator_name' => ' الأب اسطفان طعمه الكرملي'),
  array('id' => '45','translator_name' => 'د. غسان نصر'),
  array('id' => '46','translator_name' => 'د. نزار عيون السود'),
  array('id' => '47','translator_name' => 'فؤاد كامل'),
  array('id' => '48','translator_name' => 'هند خليل كلفت'),
  array('id' => '49','translator_name' => 'د. أحمد عبد العزيز سلامة'),
  array('id' => '50','translator_name' => 'محمد رمضان داود - إيمان أحمد عزب'),
  array('id' => '51','translator_name' => 'وجدى وهبة'),
  array('id' => '52','translator_name' => 'طلال الحمصي'),
  array('id' => '53','translator_name' => 'د. موسي وهبة'),
  array('id' => '54','translator_name' => 'د. ق. منيس عبد النور'),
  array('id' => '55','translator_name' => 'عبد الله حسان الانصاري'),
  array('id' => '56','translator_name' => 'محمود محمود'),
  array('id' => '57','translator_name' => 'محمد رفعت عواد'),
  array('id' => '58','translator_name' => 'د. أسامة القفاش'),
  array('id' => '59','translator_name' => 'نجيب الحصادى - محمد أحمد السيد'),
  array('id' => '60','translator_name' => 'هاشم صالح'),
  array('id' => '61','translator_name' => 'إيهاب فاروق'),
  array('id' => '62','translator_name' => 'هدي بهيج - سامي  ر. مورغان'),
  array('id' => '64','translator_name' => 'رانية أمين'),
  array('id' => '65','translator_name' => 'هاني فخري'),
  array('id' => '269','translator_name' => 'إيمان أسعد'),
  array('id' => '66','translator_name' => 'نكلس نسيم سلامة'),
  array('id' => '67','translator_name' => 'صابر احمد عبد الموجود'),
  array('id' => '68','translator_name' => 'سلام خير بك'),
  array('id' => '135','translator_name' => 'بهيج يوسف يعقوب'),
  array('id' => '70','translator_name' => 'د. كمال ميخائيل'),
  array('id' => '71','translator_name' => 'عبد المقصود عبد الكريم'),
  array('id' => '72','translator_name' => 'مكتبة جرير'),
  array('id' => '73','translator_name' => 'ناردين موريس ظريف'),
  array('id' => '74','translator_name' => 'ق. يوسف سمير'),
  array('id' => '75','translator_name' => 'مؤسسة القديس انطونيوس'),
  array('id' => '76','translator_name' => 'هدي بهيج'),
  array('id' => '77','translator_name' => 'د. نصحي عبد الشهيد'),
  array('id' => '78','translator_name' => 'الأب إيلاريون المقارى'),
  array('id' => '79','translator_name' => 'رهبان أحد أديرة برية شهيت'),
  array('id' => '80','translator_name' => 'د. أوسم وصفي'),
  array('id' => '81','translator_name' => 'سعيد فارس باز'),
  array('id' => '82','translator_name' => 'ثائر ديب'),
  array('id' => '83','translator_name' => 'سامح رهيف'),
  array('id' => '84','translator_name' => 'عصام خوري'),
  array('id' => '85','translator_name' => 'فوزى عبد المسيح'),
  array('id' => '86','translator_name' => 'د. عبد المسيح أسطفانوس'),
  array('id' => '87','translator_name' => 'جوليانا خوري'),
  array('id' => '88','translator_name' => 'د. جرجس كامل يوسف'),
  array('id' => '89','translator_name' => 'د. فنيس نقولا'),
  array('id' => '90','translator_name' => 'جورج ك. حبيب'),
  array('id' => '91','translator_name' => 'سامي رشدى مرجان'),
  array('id' => '92','translator_name' => 'فايز فضيل'),
  array('id' => '93','translator_name' => 'ماهر ناثان'),
  array('id' => '94','translator_name' => 'د. ق. كميل فتحي قلادة'),
  array('id' => '95','translator_name' => 'نشأت مرجان'),
  array('id' => '96','translator_name' => 'صموئيل وهبة - جورج عوض إبراهيم'),
  array('id' => '97','translator_name' => 'سعيد حكيم يعقوب'),
  array('id' => '98','translator_name' => ' نجاح محمود سليمان الغنيمي'),
  array('id' => '99','translator_name' => 'د. جورج عوض ابراهيم'),
  array('id' => '100','translator_name' => 'جورج صبرا'),
  array('id' => '101','translator_name' => 'خالد دويك'),
  array('id' => '102','translator_name' => 'احمد الرفاعي - فارس ضاهر'),
  array('id' => '103','translator_name' => 'سهير صبري'),
  array('id' => '104','translator_name' => 'نجيب جرجور'),
  array('id' => '105','translator_name' => 'الأب حبيب هرمز النوفلي - الأنسة أسيل جوري'),
  array('id' => '106','translator_name' => 'محمود قاسم'),
  array('id' => '107','translator_name' => 'صبري الفضل'),
  array('id' => '108','translator_name' => 'نبيل راغب'),
  array('id' => '109','translator_name' => 'لبني الريدى'),
  array('id' => '110','translator_name' => 'د. خالد البلتاجي'),
  array('id' => '111','translator_name' => 'د. يسري خميس'),
  array('id' => '112','translator_name' => 'هالة صلاح الدين'),
  array('id' => '113','translator_name' => 'أديب مصلح'),
  array('id' => '114','translator_name' => 'إيناس نبيل'),
  array('id' => '115','translator_name' => 'شريف الصيفي'),
  array('id' => '116','translator_name' => 'أديبة شكري يعقوب '),
  array('id' => '117','translator_name' => 'د. سعيد حكيم - د. جورج عوض'),
  array('id' => '118','translator_name' => 'د. سعيد حكيم - جوزيف موريس'),
  array('id' => '119','translator_name' => 'عدة مترجمين'),
  array('id' => '120','translator_name' => 'أنطوان سعيد خاطر'),
  array('id' => '121','translator_name' => 'كريستينا مجدى صابر'),
  array('id' => '122','translator_name' => 'رجاء عبدالله'),
  array('id' => '123','translator_name' => 'أ. د.ماري مسعود'),
  array('id' => '124','translator_name' => 'عادل نجيب'),
  array('id' => '125','translator_name' => 'يولاند عمانوئيل'),
  array('id' => '126','translator_name' => 'د. عصام كميل'),
  array('id' => '127','translator_name' => 'د. باسمة المنلا'),
  array('id' => '128','translator_name' => 'د. الفت حسين كحلة'),
  array('id' => '129','translator_name' => 'عبد الكريم ناصيف'),
  array('id' => '130','translator_name' => 'د. نقولا متيني'),
  array('id' => '131','translator_name' => 'نيللي شحود'),
  array('id' => '134','translator_name' => 'اليشوا حنا'),
  array('id' => '133','translator_name' => 'د. حمدي علي الفرماوي - د. رضا أبو سريع'),
  array('id' => '136','translator_name' => 'محمد حسين شمس الدين'),
  array('id' => '137','translator_name' => 'عدنان حسن'),
  array('id' => '138','translator_name' => 'سمير الشوملي'),
  array('id' => '139','translator_name' => 'لويس كامل'),
  array('id' => '140','translator_name' => 'د. سهير محفوظ'),
  array('id' => '141','translator_name' => 'د. سامي يوسف'),
  array('id' => '142','translator_name' => 'أ. د.إمام عبد الفتاح إمام'),
  array('id' => '143','translator_name' => 'د. فريد فؤاد عبد الملك'),
  array('id' => '144','translator_name' => 'إيفا وهيب'),
  array('id' => '145','translator_name' => 'داليا وهيب'),
  array('id' => '146','translator_name' => 'محمد قدري عمارة'),
  array('id' => '147','translator_name' => 'وائل محمود الهلاوي'),
  array('id' => '148','translator_name' => 'د. فاطمة نصر'),
  array('id' => '149','translator_name' => 'كوثر محمود محمد'),
  array('id' => '150','translator_name' => 'د. عزت زكي'),
  array('id' => '151','translator_name' => 'ق. بخيت متي'),
  array('id' => '152','translator_name' => 'ق. جاد المنفلوطي'),
  array('id' => '153','translator_name' => 'نجيب إلياس'),
  array('id' => '154','translator_name' => 'شوقي بشاى'),
  array('id' => '155','translator_name' => 'ق. فايز عزيز عبد الملاك'),
  array('id' => '156','translator_name' => 'ألفي فاضل'),
  array('id' => '157','translator_name' => 'ق. أنسي عبد الملك'),
  array('id' => '158','translator_name' => 'شوقي غطاس'),
  array('id' => '159','translator_name' => 'د. رضا الجمل'),
  array('id' => '160','translator_name' => 'د. عزت ذكي - ق. نشأت رفعت'),
  array('id' => '161','translator_name' => 'د. عزت عطية'),
  array('id' => '162','translator_name' => 'عادل فرج'),
  array('id' => '163','translator_name' => 'د. رضا جميل'),
  array('id' => '164','translator_name' => 'عماد ميشيل'),
  array('id' => '165','translator_name' => 'إبراهيم وطفي'),
  array('id' => '166','translator_name' => 'أمينة السعيد'),
  array('id' => '168','translator_name' => 'صبري بطرس'),
  array('id' => '169','translator_name' => 'نانسي زهجر'),
  array('id' => '170','translator_name' => 'د. فيوليت فاشة - عبلة عبد المسيح'),
  array('id' => '171','translator_name' => 'تعريب إيجلز جروب'),
  array('id' => '172','translator_name' => 'د. صلاح هلال'),
  array('id' => '173','translator_name' => 'جمعية الكتاب المقدس - لبنان'),
  array('id' => '174','translator_name' => 'د. جاد المنفلوطي'),
  array('id' => '180','translator_name' => 'فارس ضاهر'),
  array('id' => '179','translator_name' => 'د. عاطف احمد'),
  array('id' => '181','translator_name' => 'إبراهيم سلامة إبراهيم'),
  array('id' => '182','translator_name' => 'مي السيد مقلد'),
  array('id' => '183','translator_name' => 'ماريا معاد'),
  array('id' => '184','translator_name' => 'د. تيسير حسون'),
  array('id' => '185','translator_name' => 'ق. جريس دلة'),
  array('id' => '186','translator_name' => 'د. سيد محمد غنيم'),
  array('id' => '187','translator_name' => 'د. حسن مصطفي عبد المعطي'),
  array('id' => '188','translator_name' => 'د. ستيفن فوزى'),
  array('id' => '189','translator_name' => 'كتاب الهلال'),
  array('id' => '190','translator_name' => 'نيفين نصر'),
  array('id' => '191','translator_name' => 'د. محمد عبد الظاهر الطيب'),
  array('id' => '192','translator_name' => 'دار النشر المعمدانية'),
  array('id' => '193','translator_name' => 'د. يوسف مراد'),
  array('id' => '194','translator_name' => 'د. أمير بقطر'),
  array('id' => '195','translator_name' => 'نادين عطار '),
  array('id' => '196','translator_name' => 'صلاح مراد'),
  array('id' => '197','translator_name' => 'د. إيناس لمعي'),
  array('id' => '198','translator_name' => 'د. عبد العلي الجسماني '),
  array('id' => '199','translator_name' => 'يوسف ميخائيل أسعد'),
  array('id' => '200','translator_name' => 'د. محمد عثمان نجاتي'),
  array('id' => '201','translator_name' => 'سامية القطان - حسام عزب'),
  array('id' => '202','translator_name' => 'د. طلعت منصور'),
  array('id' => '203','translator_name' => 'د. عبد المنعم الحفني '),
  array('id' => '204','translator_name' => 'رمسيس عوض'),
  array('id' => '205','translator_name' => 'د. أحمد مستجير'),
  array('id' => '206','translator_name' => 'د. لطفية عاشور '),
  array('id' => '207','translator_name' => 'شوقي جلال'),
  array('id' => '208','translator_name' => 'خيري حماد'),
  array('id' => '209','translator_name' => 'نهاد رضا'),
  array('id' => '210','translator_name' => 'محمد علي اليوسفي'),
  array('id' => '211','translator_name' => 'حسن بلاسم - عدنان المبارك'),
  array('id' => '212','translator_name' => 'مني أبو سنة'),
  array('id' => '213','translator_name' => 'محسن فرجاني'),
  array('id' => '214','translator_name' => 'د. تمام حسان'),
  array('id' => '215','translator_name' => 'حياة الحويك عطية'),
  array('id' => '216','translator_name' => 'مجدي عبد الحافظ'),
  array('id' => '217','translator_name' => 'د. عبد السلام القفاش - د. سامي محمود علي '),
  array('id' => '268','translator_name' => 'ليلي النابلسي'),
  array('id' => '229','translator_name' => 'د. نيفين غراب '),
  array('id' => '221','translator_name' => 'د. مي حداد'),
  array('id' => '222','translator_name' => 'عبد العزيز توفيق جاويد'),
  array('id' => '223','translator_name' => 'قسطندي شوملي'),
  array('id' => '224','translator_name' => 'رمزي عباد'),
  array('id' => '225','translator_name' => 'د. رمسيس شحاتة'),
  array('id' => '226','translator_name' => 'إبراهيم حافظ- السيد محمد عثمان - سامي علي الجمال'),
  array('id' => '227','translator_name' => 'د. حاتم عبد الصاحب '),
  array('id' => '228','translator_name' => 'أمجد أنور'),
  array('id' => '230','translator_name' => 'د. أنيس فريحة'),
  array('id' => '231','translator_name' => 'جوزيف صابر'),
  array('id' => '232','translator_name' => 'د. حسن حنفي حسنين'),
  array('id' => '233','translator_name' => 'كامل يوسف حسين'),
  array('id' => '234','translator_name' => 'فؤاد كامل - محمود رجب'),
  array('id' => '235','translator_name' => 'سعد زهران'),
  array('id' => '236','translator_name' => 'سامي علام'),
  array('id' => '237','translator_name' => 'د. عادل مصطفي '),
  array('id' => '238','translator_name' => 'د. عبد الهادي عبد الرحمن'),
  array('id' => '239','translator_name' => 'نبيل محسن'),
  array('id' => '240','translator_name' => 'د. إيمان فوزى'),
  array('id' => '241','translator_name' => 'ليلي الجبالي '),
  array('id' => '242','translator_name' => 'احمد إسماعيل صبح - منير فوزى'),
  array('id' => '243','translator_name' => 'رنا النوري'),
  array('id' => '244','translator_name' => 'د. جمال محمد - سعيد الخطيب'),
  array('id' => '245','translator_name' => 'مركز التعريب والترجمة'),
  array('id' => '246','translator_name' => 'د. لطفي فطيم'),
  array('id' => '247','translator_name' => 'د. محمد نجيب أحمد الصبوة'),
  array('id' => '248','translator_name' => 'د. جمعة سيد يوسف'),
  array('id' => '249','translator_name' => 'سميرة أبو الحسن'),
  array('id' => '250','translator_name' => 'د. طلعت منصور - د. عادل عز الدين'),
  array('id' => '251','translator_name' => 'د. قدري حنفي - د. لطفي فهيم'),
  array('id' => '252','translator_name' => 'د. فرج أحمد فرج'),
  array('id' => '253','translator_name' => 'سامي محمود علي - د. عبد السلام القفاش'),
  array('id' => '254','translator_name' => 'بو علي ياسين- علي ياسين'),
  array('id' => '255','translator_name' => 'د. أماني سمير - حنا يوسف'),
  array('id' => '256','translator_name' => 'د. السيد محمد خيري - سمير نعيم - فرج أحمد فرج'),
  array('id' => '257','translator_name' => 'طلعت مطر '),
  array('id' => '258','translator_name' => 'د. صفاء الأعسر /د.. علاء الدين كفافي/د. عزيزة السيد/ د. فيصل يونس /د. فادية علوان/د. سهير غباشي'),
  array('id' => '259','translator_name' => 'نعيم عشم'),
  array('id' => '260','translator_name' => 'د. ياسر العيتي'),
  array('id' => '261','translator_name' => 'فريدا حداد الطويل'),
  array('id' => '262','translator_name' => 'المطران بولس الصباغ'),
  array('id' => '263','translator_name' => 'فوزى جرجس حنا'),
  array('id' => '264','translator_name' => 'د. جورج أنسي'),
  array('id' => '265','translator_name' => 'د. جمعة سيد يوسف- د. محمد نجيب - أحمد الصبوة'),
  array('id' => '266','translator_name' => 'د. فرج أحمد فرج/ د. قدري حفني /د. لطيف فهيم'),
  array('id' => '267','translator_name' => 'أمل سليم'),
  array('id' => '270','translator_name' => 'الأب صلاح أبو جودة اليسوعي'),
  array('id' => '271','translator_name' => 'ق. عزت شاكر'),
  array('id' => '272','translator_name' => 'ق. الفريد فائق صموئيل'),
  array('id' => '273','translator_name' => 'يوسف قسطة'),
  array('id' => '274','translator_name' => 'د. شريف شاكر'),
  array('id' => '275','translator_name' => 'عبد المنعم الزيادي'),
  array('id' => '276','translator_name' => 'الخوري نبيل الحاج'),
  array('id' => '277','translator_name' => 'ماري جوزيف'),
  array('id' => '278','translator_name' => 'د. طلال عتريسي'),
  array('id' => '282','translator_name' => 'د. سلوي الملا'),
  array('id' => '280','translator_name' => 'محمود منقذ الهاشمي'),
  array('id' => '281','translator_name' => 'صلاح حاتم'),
  array('id' => '283','translator_name' => 'جاكلين مجدي'),
  array('id' => '284','translator_name' => 'صفاء الأعسر'),
  array('id' => '285','translator_name' => 'د. زكريا فاخوري'),
  array('id' => '286','translator_name' => 'مريان صموئيل كتكوت'),
  array('id' => '287','translator_name' => 'د. لويس كامل- إيفا وهيب'),
  array('id' => '288','translator_name' => 'د. محمد خليفة بركات'),
  array('id' => '289','translator_name' => 'د. محمد نسيم رأفت'),
  array('id' => '290','translator_name' => 'د. السيد محمد خيري'),
  array('id' => '291','translator_name' => 'أحمد ذكي محمد'),
  array('id' => '292','translator_name' => 'د. جرجس ميلاد- د. زكريا فاخوري'),
  array('id' => '293','translator_name' => 'ق. مدحت صبري'),
  array('id' => '294','translator_name' => 'حليم عبد الله - انطوان طعمه'),
  array('id' => '295','translator_name' => 'صلاح شوقي'),
  array('id' => '296','translator_name' => 'إيناس توفيق'),
  array('id' => '297','translator_name' => 'د. نظمي لوقا'),
  array('id' => '298','translator_name' => 'مايكل كوبرسن - اسامة خليل'),
  array('id' => '299','translator_name' => 'د. زكريا عوض الله'),
  array('id' => '300','translator_name' => 'سونيا المنقبادي'),
  array('id' => '301','translator_name' => 'علي عفيفي'),
  array('id' => '302','translator_name' => 'نيفين رمسيس'),
  array('id' => '303','translator_name' => 'د. ميخائيل أسعد -د. عبد الرازق جعفر'),
  array('id' => '304','translator_name' => 'ماهر ناثان - نشأت رفعت'),
  array('id' => '305','translator_name' => 'هايدي فوزى'),
  array('id' => '306','translator_name' => 'الأب جرجس المارديني'),
  array('id' => '307','translator_name' => 'ملك مرسي حماد'),
  array('id' => '308','translator_name' => 'د. سلوي جادو'),
  array('id' => '309','translator_name' => 'فاطمة عصام صبري '),
  array('id' => '310','translator_name' => 'سمير محفوظ بشير'),
  array('id' => '311','translator_name' => 'ق. حرز ذكي'),
  array('id' => '312','translator_name' => 'د. نبيلة حنا فريد- د. ق. صفاء داود'),
  array('id' => '313','translator_name' => 'منشورات دار منهل الحياه'),
  array('id' => '314','translator_name' => 'د. عادل ذكري'),
  array('id' => '315','translator_name' => 'يوسف شكري'),
  array('id' => '317','translator_name' => 'د. وفاء فوزى'),
  array('id' => '318','translator_name' => 'د. سعيد حكيم يعقوب'),
  array('id' => '319','translator_name' => 'أحمد لطفي'),
  array('id' => '320','translator_name' => 'محمد حبيب'),
  array('id' => '321','translator_name' => 'رفيق غدار'),
  array('id' => '322','translator_name' => 'د. محمد أحمد خطاب'),
  array('id' => '323','translator_name' => 'نزيه الحكيم'),
  array('id' => '324','translator_name' => 'د. صلاح مخيمر - عبده ميخائيل رزق'),
  array('id' => '325','translator_name' => 'إيجلز جروب'),
  array('id' => '326','translator_name' => 'أ.د.طارق أسعد- د. الفت كمال'),
  array('id' => '327','translator_name' => 'ق. عاطف المرفوض'),
  array('id' => '328','translator_name' => 'صفوت فرج'),
  array('id' => '330','translator_name' => ''),
  array('id' => '331','translator_name' => 'جوزيت الشعار مشنتف'),
  array('id' => '332','translator_name' => 'أحمد رمو'),
  array('id' => '333','translator_name' => 'ندرة البازجي'),
  array('id' => '334','translator_name' => 'محمد خليل حسين'),
  array('id' => '335','translator_name' => 'د. فرج أحمد فرج - د. قدري حفني _ د. لطفي فطيم'),
  array('id' => '336','translator_name' => 'أ.د.طارق أسعد- د. الفت كحلة'),
  array('id' => '337','translator_name' => 'د. خالد العمري'),
  array('id' => '338','translator_name' => 'د. جمعة سيد يوسف- د. محمد نجيب الصبوة'),
  array('id' => '339','translator_name' => 'محمد رفعت رمضان - نجيب اسكندر إبراهيم'),
  array('id' => '340','translator_name' => 'د. محمود عيد مصطفي'),
  array('id' => '341','translator_name' => 'د. محمد غطاس'),
  array('id' => '342','translator_name' => 'صالح علماني'),
  array('id' => '343','translator_name' => 'محمد عناني'),
  array('id' => '344','translator_name' => 'د. شكري محمد عياد'),
  array('id' => '345','translator_name' => 'فوزية العشماوي'),
  array('id' => '346','translator_name' => 'نانسي سمير'),
  array('id' => '348','translator_name' => 'د. محمد مصطفي بدوي'),
  array('id' => '349','translator_name' => 'المكتبة الثقافية'),
  array('id' => '350','translator_name' => 'أنيس ذكي حسن'),
  array('id' => '351','translator_name' => 'منيرة كروان'),
  array('id' => '352','translator_name' => 'د. سهيل إدريس'),
  array('id' => '353','translator_name' => 'دار الآداب -بيروت'),
  array('id' => '354','translator_name' => 'مراد الزمر'),
  array('id' => '355','translator_name' => 'محمد عيد إبراهيم'),
  array('id' => '356','translator_name' => 'سعد زغلول نصار'),
  array('id' => '357','translator_name' => 'أنطونيوس بشير'),
  array('id' => '358','translator_name' => 'بول شاوول'),
  array('id' => '359','translator_name' => 'د. انجيل بطرس'),
  array('id' => '360','translator_name' => 'توفيق علي منصور'),
  array('id' => '361','translator_name' => 'حسن عثمان'),
  array('id' => '363','translator_name' => 'د. محمد عناني'),
  array('id' => '364','translator_name' => 'محمد العزب موسي'),
  array('id' => '365','translator_name' => 'لطفي سلطان'),
  array('id' => '366','translator_name' => 'جميل جبر'),
  array('id' => '367','translator_name' => 'نادية البنهاوي'),
  array('id' => '368','translator_name' => 'الشريف خاطر'),
  array('id' => '369','translator_name' => 'عز الدين بنهاوي'),
  array('id' => '370','translator_name' => 'أحمد عمر شاهين'),
  array('id' => '371','translator_name' => 'هاشم الحسيني'),
  array('id' => '372','translator_name' => 'عايدة مطرجي ادريس'),
  array('id' => '373','translator_name' => 'ليلي محمد عثمان نجاتي'),
  array('id' => '374','translator_name' => 'عبد السلام شحاتة'),
  array('id' => '375','translator_name' => 'مصطفي ماهر'),
  array('id' => '376','translator_name' => 'د. سامي  الدروبي'),
  array('id' => '377','translator_name' => 'محمد حافظ إبراهيم'),
  array('id' => '378','translator_name' => 'ناريمان الشاملي'),
  array('id' => '379','translator_name' => 'عبد الوهاب الشيخ'),
  array('id' => '380','translator_name' => 'خالد البلتاجي'),
  array('id' => '381','translator_name' => 'مصطفي السقا - سعيد جودة'),
  array('id' => '382','translator_name' => 'عبد الغفار مكاوي'),
  array('id' => '383','translator_name' => 'عز الدين محمود'),
  array('id' => '384','translator_name' => 'مني مكرم - وجدي وهبة'),
  array('id' => '385','translator_name' => 'مكرم روبيل'),
  array('id' => '386','translator_name' => 'إيناس صادق - لميس الراعي '),
  array('id' => '387','translator_name' => 'إيرين خليل إبراهيم'),
  array('id' => '394','translator_name' => 'د. فؤاد البهي السيد'),
  array('id' => '389','translator_name' => 'ماهر نيكلس - إيرين خليل إبراهيم'),
  array('id' => '390','translator_name' => 'دينا خيري'),
  array('id' => '391','translator_name' => 'مينا مدحت - فادي فيكتور'),
  array('id' => '392','translator_name' => 'خالد زايد'),
  array('id' => '393','translator_name' => 'ميادة منير'),
  array('id' => '395','translator_name' => 'د. سعيد عبده'),
  array('id' => '396','translator_name' => 'د. إبراهيم حافظ'),
  array('id' => '397','translator_name' => 'د. عطية محمود هنا'),
  array('id' => '398','translator_name' => 'السيد محمد عثمان'),
  array('id' => '399','translator_name' => 'د. عبد المنعم المليجي'),
  array('id' => '400','translator_name' => 'العميد سيد عبد الحميد مرسي'),
  array('id' => '401','translator_name' => 'د. سعد دياب'),
  array('id' => '402','translator_name' => 'سامي علي الجمال'),
  array('id' => '403','translator_name' => 'سامي ناشد'),
  array('id' => '404','translator_name' => 'صلاح الدين لطفي '),
  array('id' => '405','translator_name' => 'عبد الفتاح المنياوي'),
  array('id' => '406','translator_name' => 'د. محمد أحمد الغنام'),
  array('id' => '407','translator_name' => 'د. محمد لبيب النجيحي'),
  array('id' => '408','translator_name' => 'السيد محمد العزاوي'),
  array('id' => '409','translator_name' => 'أيهم الصباغ'),
  array('id' => '410','translator_name' => 'ألفيرا عون'),
  array('id' => '411','translator_name' => 'د. محمدعبد العليم مرسي'),
  array('id' => '412','translator_name' => 'د. عقيل الشيخ حسين'),
  array('id' => '413','translator_name' => 'ماريانا كتكوت'),
  array('id' => '414','translator_name' => 'هاني حنا'),
  array('id' => '415','translator_name' => 'فينيس نقولا'),
  array('id' => '416','translator_name' => 'د. سامح بيومي السباعي '),
  array('id' => '417','translator_name' => 'د. رمزي سعد'),
  array('id' => '418','translator_name' => 'مكتبة المنار'),
  array('id' => '419','translator_name' => 'طانيوس زخاري'),
  array('id' => '420','translator_name' => 'لوسي عياد بباوي'),
  array('id' => '421','translator_name' => 'فخري كرم يوسف'),
  array('id' => '422','translator_name' => 'يوسف سركيس'),
  array('id' => '423','translator_name' => 'فرج عزت حكيم'),
  array('id' => '424','translator_name' => 'ناجي يوسف'),
  array('id' => '425','translator_name' => 'رضا رمسيس حنا'),
  array('id' => '426','translator_name' => 'الأب وفيق حبيب نصري'),
  array('id' => '427','translator_name' => 'د. مراد عزيز'),
  array('id' => '428','translator_name' => 'د. جوزيف لويز'),
  array('id' => '429','translator_name' => 'جانيت ادوارد نصيف'),
  array('id' => '430','translator_name' => 'د. عادل كمال'),
  array('id' => '431','translator_name' => 'يعقوب أخنوخ سمعان'),
  array('id' => '432','translator_name' => 'يوسف فرج الله '),
  array('id' => '433','translator_name' => 'د. فؤاد .ك . بولس - لويس كامل'),
  array('id' => '434','translator_name' => 'سامي حنا غبريال'),
  array('id' => '435','translator_name' => 'د. هناء عزيز حبيب'),
  array('id' => '436','translator_name' => 'أمير أديب'),
  array('id' => '437','translator_name' => 'ايبون لبيب سليمان'),
  array('id' => '438','translator_name' => 'دار الكرمة الحقيقية للنشر والترجمة'),
  array('id' => '439','translator_name' => 'مرام نافع طحان'),
  array('id' => '440','translator_name' => 'أ.د. طارق أسعد'),
  array('id' => '441','translator_name' => 'وفيق مازن'),
  array('id' => '442','translator_name' => 'د. نبيلة حنا'),
  array('id' => '443','translator_name' => 'مرسا فرعون'),
  array('id' => '444','translator_name' => 'فاتن صبح'),
  array('id' => '445','translator_name' => 'آمال الأتات'),
  array('id' => '447','translator_name' => 'أفنان محمد سعد الدين'),
  array('id' => '448','translator_name' => 'نسيم مجلي'),
  array('id' => '449','translator_name' => 'أحمد حسان'),
  array('id' => '450','translator_name' => 'محمد عوض محمد'),
  array('id' => '451','translator_name' => 'الرابطة الإنجيلية في الشرق الأوسط'),
  array('id' => '452','translator_name' => 'راهب من البرية الغربية'),
  array('id' => '453','translator_name' => 'عصام زكريا جميل'),
  array('id' => '454','translator_name' => 'د. لورانس لمعي رزق الله'),
  array('id' => '455','translator_name' => 'لويس عوض'),
  array('id' => '456','translator_name' => 'ماهر شفيق فريد'),
  array('id' => '457','translator_name' => 'محب سعد إبراهيم'),
  array('id' => '458','translator_name' => 'جرجس منسي'),
  array('id' => '459','translator_name' => 'فوزية محمد بدران'),
  array('id' => '460','translator_name' => 'أ.د. معتز سيد عبد الله'),
  array('id' => '461','translator_name' => 'الحرية للنشر و التوزيع'),
  array('id' => '462','translator_name' => 'مريم شادي جورج'),
  array('id' => '463','translator_name' => 'ر.ع.'),
  array('id' => '464','translator_name' => 'قحطان جاسم'),
  array('id' => '465','translator_name' => 'مريم سامر الأيوبي'),
  array('id' => '466','translator_name' => 'عادل زعيتر'),
  array('id' => '467','translator_name' => 'السيد محمد بدوي'),
  array('id' => '468','translator_name' => 'سمية رمضان'),
  array('id' => '469','translator_name' => 'د. إلياس حاجوج'),
  array('id' => '470','translator_name' => 'ليلي عبد الرازق'),
  array('id' => '471','translator_name' => 'د. مصطفي إراهيم فهمي'),
  array('id' => '472','translator_name' => 'إبراهيم مطر'),
  array('id' => '473','translator_name' => 'ق. مرقس داود'),
  array('id' => '474','translator_name' => 'ثابت رزق الله'),
  array('id' => '475','translator_name' => 'راعوث  آرساني'),
  array('id' => '476','translator_name' => 'د, إيمان البرت'),
  array('id' => '477','translator_name' => 'ق. حبيب حكيم'),
  array('id' => '478','translator_name' => 'الأب كميل حشيمة اليسوعي'),
  array('id' => '479','translator_name' => 'دار النشر الأسقفية'),
  array('id' => '480','translator_name' => 'الأب ك. يوسف بربي اليسوعي'),
  array('id' => '481','translator_name' => 'فؤاد ذكي'),
  array('id' => '482','translator_name' => 'واصف عبد الملك'),
  array('id' => '483','translator_name' => 'بشاي مسعد'),
  array('id' => '484','translator_name' => 'د. وديع ميخائيل'),
  array('id' => '485','translator_name' => 'د. مدحت أديب'),
  array('id' => '486','translator_name' => 'صبري مسعد غبريال '),
  array('id' => '487','translator_name' => 'رضا لمعي الجمل'),
  array('id' => '488','translator_name' => 'مطبوعات المجلس العام للكنائس الرسولية'),
  array('id' => '489','translator_name' => 'نزيه خاطر'),
  array('id' => '490','translator_name' => 'هالة عزيز'),
  array('id' => '491','translator_name' => 'ساندرا عزب'),
  array('id' => '492','translator_name' => 'د. كرم ناشد'),
  array('id' => '493','translator_name' => 'الأب حبيب هرمز النوفلي'),
  array('id' => '494','translator_name' => 'عدلي فام'),
  array('id' => '495','translator_name' => 'نادر حنا'),
  array('id' => '496','translator_name' => 'د. نيفين سعد'),
  array('id' => '497','translator_name' => 'راهب من البرية الشرقية'),
  array('id' => '498','translator_name' => 'تانيا ناجيا'),
  array('id' => '499','translator_name' => 'حمزة ين قبلان المزيني'),
  array('id' => '500','translator_name' => 'إيزابيل كمال'),
  array('id' => '501','translator_name' => 'أحمد حيدر'),
  array('id' => '502','translator_name' => 'فؤاد كامل عبد العزيز'),
  array('id' => '503','translator_name' => 'عبد القادر قنيني'),
  array('id' => '504','translator_name' => 'الأرشمندريت أنطونيوس بشير'),
  array('id' => '505','translator_name' => 'زكي نجيب محمود'),
  array('id' => '506','translator_name' => 'د. عادل دمرداش'),
  array('id' => '507','translator_name' => 'هند صابر مهدي'),
  array('id' => '508','translator_name' => 'نيفين اسكندر'),
  array('id' => '509','translator_name' => 'لوئيس حداد'),
  array('id' => '510','translator_name' => 'بولس رعد'),
  array('id' => '511','translator_name' => 'مروة عبد السلام'),
  array('id' => '512','translator_name' => 'مصطفي محمد فؤاد'),
  array('id' => '513','translator_name' => 'عبد الحميد الجمال'),
  array('id' => '514','translator_name' => 'ياسر حسن'),
  array('id' => '515','translator_name' => 'علي محمود مقلد'),
  array('id' => '516','translator_name' => 'هاني صالح'),
  array('id' => '517','translator_name' => 'إيمن فؤاد زهري'),
  array('id' => '518','translator_name' => 'سهي الشامي'),
  array('id' => '519','translator_name' => 'نهي بهمن'),
  array('id' => '520','translator_name' => 'خالد الجبيلي'),
  array('id' => '521','translator_name' => 'شيري عوض'),
  array('id' => '524','translator_name' => 'دار الثقافة'),
  array('id' => '525','translator_name' => 'دار منهل الحياة'),
  array('id' => '526','translator_name' => 'وليم جندي'),
  array('id' => '527','translator_name' => 'كنيسة مارجرجس سبورتنج'),
  array('id' => '528','translator_name' => 'الأب  البير ابونا العراقي'),
  array('id' => '529','translator_name' => 'مؤسسة القديس أنطونيوس'),
  array('id' => '530','translator_name' => 'هاني غاوي'),
  array('id' => '531','translator_name' => 'جوزيف لويس'),
  array('id' => '532','translator_name' => 'سلام منير حبيب'),
  array('id' => '533','translator_name' => 'دار الفاروق'),
  array('id' => '534','translator_name' => 'د. أميرة حلمي مطر'),
  array('id' => '535','translator_name' => 'د. عثمان أمين'),
  array('id' => '536','translator_name' => 'توفيق مجلي'),
  array('id' => '537','translator_name' => 'عبد المنعم الحفني'),
  array('id' => '538','translator_name' => 'د. عطيه محمود هنا- د. ماهر كامل'),
  array('id' => '539','translator_name' => 'د. عبد الغفار مكاوي'),
  array('id' => '540','translator_name' => 'د. حسن حماد'),
  array('id' => '541','translator_name' => 'حبيب الشاروني'),
  array('id' => '542','translator_name' => 'محمد لطفي جمعة'),
  array('id' => '543','translator_name' => 'محمود رجب'),
  array('id' => '544','translator_name' => 'إسماعيل المصدق'),
  array('id' => '545','translator_name' => 'الخوري أسقف يوحنا الحلو'),
  array('id' => '546','translator_name' => 'د. محمد عضيمة'),
  array('id' => '547','translator_name' => 'فليكس فارس'),
  array('id' => '548','translator_name' => 'الشيخ فايز فضيل'),
  array('id' => '549','translator_name' => 'القس الأرشد ياكون رفيق فرح وقرينته السيدة نجوي فرح'),
  array('id' => '550','translator_name' => 'وجيه يوسف'),
  array('id' => '551','translator_name' => 'د. وهبه طلعت أبو العلا'),
  array('id' => '552','translator_name' => 'د. هبه طلعت أبو العلا '),
  array('id' => '553','translator_name' => 'د. عماد موريس أسكندر'),
  array('id' => '554','translator_name' => 'نكلس نسيم- د. كمال ميخائيل- إدوارد وديع عبد المسيح - وليم وهبه بباوي'),
  array('id' => '555','translator_name' => 'ميشيل وديع - يولاند يسري'),
  array('id' => '556','translator_name' => 'هيئة الخدمة الروحية وتدريب القادة'),
  array('id' => '557','translator_name' => 'مركز دراسة الأباء'),
  array('id' => '558','translator_name' => 'كلية اللاهوت الإنجيلية للشرق الأوسط للكنائس الرسولية'),
  array('id' => '559','translator_name' => 'hrefaat.word press.com'),
  array('id' => '560','translator_name' => 'مركز مورجان للنشر والأعلام -بيروت - لبنان'),
  array('id' => '561','translator_name' => 'ق. حمدي سعد'),
  array('id' => '562','translator_name' => 'د. وليم سليمان قلادة'),
  array('id' => '563','translator_name' => 'زكي مسيحة'),
  array('id' => '564','translator_name' => 'د. فيكتور صموئيل بدروس'),
  array('id' => '565','translator_name' => 'د. ق. فهيم عزيز'),
  array('id' => '566','translator_name' => 'رجاء نوصير'),
  array('id' => '567','translator_name' => 'ق. بهيج خوري'),
  array('id' => '568','translator_name' => 'ق. ريد زخاري'),
  array('id' => '569','translator_name' => 'ق. عبد الكريم كيرلس'),
  array('id' => '570','translator_name' => 'أميرة سيدهم'),
  array('id' => '571','translator_name' => 'سعد مقاري'),
  array('id' => '572','translator_name' => 'سليم اسكندر - حنا يوسف'),
  array('id' => '573','translator_name' => 'رشدي فيلبس'),
  array('id' => '574','translator_name' => 'المنشورات المعمدانية'),
  array('id' => '575','translator_name' => 'عيسي طنوس'),
  array('id' => '576','translator_name' => 'لوجوس'),
  array('id' => '577','translator_name' => 'سويلم سيدهم'),
  array('id' => '578','translator_name' => 'الخوري يوسف العلم'),
  array('id' => '579','translator_name' => 'د. موريس تاوضروس - د. نصحي عبد الشهيد'),
  array('id' => '580','translator_name' => 'عزرا مرجان'),
  array('id' => '581','translator_name' => 'أبنا إيساك'),
  array('id' => '582','translator_name' => 'الأب جورج خوام البولسي'),
  array('id' => '583','translator_name' => 'الأب فيكتور شلحت اليسوعي'),
  array('id' => '584','translator_name' => 'د. نبيه فريز'),
  array('id' => '585','translator_name' => 'صموئيل كامل عبد السيد - نصحي عبد الشهيد بطرس'),
  array('id' => '586','translator_name' => 'إحدي الراهبات'),
  array('id' => '587','translator_name' => 'جورج عوض'),
  array('id' => '588','translator_name' => 'ق. صمويئل وهبه- د. جورج عوض إبراهيم'),
  array('id' => '589','translator_name' => 'د. أحمد فؤاد كامل'),
  array('id' => '591','translator_name' => 'ق. جورج  ك. حبيب'),
  array('id' => '592','translator_name' => 'نجاح محمود سليمان الغنيمي - الأب أنخل رود ريجث اندلوث الكرملي'),
  array('id' => '593','translator_name' => 'نجاح محمود سليمان الغنيمي - الأب أنخل رود ريجث اندلوث الكرملي'),
  array('id' => '594','translator_name' => 'رسالة القديسة تريزا ليسوع الطفل'),
  array('id' => '595','translator_name' => 'د. زكي نجيب محمود - محمد بدران'),
  array('id' => '596','translator_name' => 'محمد بدران - د. عبد الحميد يونس'),
  array('id' => '597','translator_name' => 'محمد بدران'),
  array('id' => '598','translator_name' => 'د. عبد الحميد يونس'),
  array('id' => '599','translator_name' => 'د. عبد الحميد يونس - محمد علي أبو درة'),
  array('id' => '600','translator_name' => 'فؤاد أندراوس - محمد علي أبو درة'),
  array('id' => '601','translator_name' => 'فؤاد أندراوس '),
  array('id' => '602','translator_name' => 'الكنيسة   الإنجيلية بقصر الدوبارة - كلية فاريتاس'),
  array('id' => '603','translator_name' => 'الكنيسة   الإنجيلية بقصر الدوبارة - كلية فاريتاس'),
  array('id' => '604','translator_name' => 'وليم وهبه - جوزيف صابر - صبري بطرس - عاطف سامي'),
  array('id' => '605','translator_name' => 'د. فتح الله محمد المشعشع'),
  array('id' => '606','translator_name' => 'وليم وهبه - جوزيف صابر - صبري بطرس - عاطف سامي - عادل كمال'),
  array('id' => '607','translator_name' => 'عصام خوري - سمير الشوملي '),
  array('id' => '608','translator_name' => 'نكلس نسيم سلامة - ق. بولس عزيز - محمد حسن غنيم - إيفيت صليب - كميلة شمعون إيليا - ق. منير صبحي يعقوب'),
  array('id' => '621','translator_name' => 'صبري بطرس - أمجد الياس - نبيلة حنا - وئام سليم'),
  array('id' => '610','translator_name' => 'أمجد أنور - جورج جابر - جوزيف صابر - رافت وجدي - صبري بطرس - هدي أديب'),
  array('id' => '611','translator_name' => 'د. إمتثال هادي الجويلة - د. فاطمة سلامة عياد - د. هناء شويخ - د. ملك جاسم الرشيد - د. نادية عبداللاه'),
  array('id' => '612','translator_name' => 'د. جورج نوار'),
  array('id' => '613','translator_name' => 'نجيب وهبه'),
  array('id' => '614','translator_name' => 'سعاد سوريال'),
  array('id' => '615','translator_name' => 'صبحي مقار'),
  array('id' => '616','translator_name' => 'ق. بنيامين مرجان'),
  array('id' => '617','translator_name' => 'أديب يسي'),
  array('id' => '618','translator_name' => 'ق. حارث فريصة'),
  array('id' => '619','translator_name' => 'ق. يوسف فليحان ب.ع.  - ق. يعقوب خضر ب.ع.'),
  array('id' => '620','translator_name' => 'مركز المطبوعات المسيحية'),
  array('id' => '622','translator_name' => 'ق. رضا عدلي'),
  array('id' => '623','translator_name' => 'الكنيسة   الإنجيلية بقصر الدوبارة '),
  array('id' => '625','translator_name' => 'الترجمة الحديثة للكتاب المقدس'),
  array('id' => '626','translator_name' => 'أحمد العلي'),
  array('id' => '627','translator_name' => 'أنور محمد إبراهيم'),
  array('id' => '628','translator_name' => 'معاني صالح'),
  array('id' => '629','translator_name' => 'رندة حكيم - شيرين عبد الوهاب'),
  array('id' => '630','translator_name' => 'نجم والي'),
  array('id' => '631','translator_name' => 'علاء الديب'),
  array('id' => '632','translator_name' => 'يوسف نبيل'),
  array('id' => '633','translator_name' => 'محمود محمد الخضيري'),
  array('id' => '634','translator_name' => 'عمرو حشمت - محمود خيال'),
  array('id' => '635','translator_name' => 'يوسف توما الدومنيكاني'),
  array('id' => '636','translator_name' => 'عنايات عبد العزيز'),
  array('id' => '637','translator_name' => 'أحمد عثمان'),
  array('id' => '638','translator_name' => 'محمد رشاد خميس - ماهر فؤاد جويجاتي'),
  array('id' => '639','translator_name' => 'د. مصطفي ماهر'),
  array('id' => '640','translator_name' => 'ناهد يوسف'),
  array('id' => '641','translator_name' => 'د.رحاب عكاوي'),
  array('id' => '642','translator_name' => 'مهدي بندق'),
  array('id' => '643','translator_name' => 'محمد مصطفي بدوي'),
  array('id' => '644','translator_name' => 'خليل مطران'),
  array('id' => '645','translator_name' => 'عثمان نويه'),
  array('id' => '646','translator_name' => 'كاترين سرور'),
  array('id' => '647','translator_name' => 'سارة السباعي'),
  array('id' => '648','translator_name' => 'وائل اليان حداد'),
  array('id' => '649','translator_name' => 'ق. رامي ناير - د. فينيس نقولا- هدي بهيج'),
  array('id' => '650','translator_name' => 'عبد السلام عليه'),
  array('id' => '651','translator_name' => 'الدسوقي فهمي'),
  array('id' => '652','translator_name' => 'إسماعيل مظهر'),
  array('id' => '653','translator_name' => 'د. محمد أحمد غالي'),
  array('id' => '654','translator_name' => 'د. ممدوحة محمد سلامة'),
  array('id' => '655','translator_name' => 'إميل خليل بيدس'),
  array('id' => '656','translator_name' => 'ق. موسي وهبه وآخرون'),
  array('id' => '657','translator_name' => 'صبري بطرس - أمجد أنور - هنري أديب '),
  array('id' => '658','translator_name' => 'إيريني مكرم صموئيل'),
  array('id' => '659','translator_name' => 'محمد التهامي العماري'),
  array('id' => '660','translator_name' => 'حكمت لميا'),
  array('id' => '661','translator_name' => 'لطفي فطيم - عادل دمرداش'),
  array('id' => '662','translator_name' => ' رحاب ولي الدين - دعاء الحفناوي'),
  array('id' => '663','translator_name' => 'د. مراد علي عيسي'),
  array('id' => '664','translator_name' => 'أحمد الصاوي محمد'),
  array('id' => '665','translator_name' => 'سامح عزمي'),
  array('id' => '666','translator_name' => 'كاثي سوكيس'),
  array('id' => '667','translator_name' => 'عبد الودود محمود العلي'),
  array('id' => '668','translator_name' => 'د. حامد عبد العزيز الفقي'),
  array('id' => '669','translator_name' => 'حسين محمد القباني'),
  array('id' => '670','translator_name' => 'عباس حافظ'),
  array('id' => '671','translator_name' => 'عصام الدين حفني ناصف'),
  array('id' => '672','translator_name' => 'زغلول فهمي'),
  array('id' => '673','translator_name' => 'سعد الغزالي'),
  array('id' => '674','translator_name' => 'فاروق حلمي'),
  array('id' => '675','translator_name' => 'أحمد أمين'),
  array('id' => '676','translator_name' => 'مروة المغربي '),
  array('id' => '677','translator_name' => 'جنات جمال'),
  array('id' => '678','translator_name' => 'راهب من دير الأنبا أنطونيوس'),
  array('id' => '679','translator_name' => 'خدمة الحق يحرركم'),
  array('id' => '680','translator_name' => 'شيري عوض - صموئيل ابراهيم وآخرين '),
  array('id' => '681','translator_name' => 'إليزابيث فايز- شيري عوض وآخرين'),
  array('id' => '682','translator_name' => 'د. محمود حب الله'),
  array('id' => '683','translator_name' => 'ناصر ناصر'),
  array('id' => '684','translator_name' => 'دار نشر معهد عمواس'),
  array('id' => '685','translator_name' => 'الأخت حكيمة خوري'),
  array('id' => '686','translator_name' => 'محمد نجيب أحمد الصبوة'),
  array('id' => '687','translator_name' => 'راقية الدويك'),
  array('id' => '688','translator_name' => 'ماجد زاخر'),
  array('id' => '689','translator_name' => 'ق. أديب عوض-ق. وليد هرموش- ق.د. فيكتور مكاري'),
  array('id' => '690','translator_name' => 'سلمي محمد سعد'),
  array('id' => '692','translator_name' => 'إيهاب عبد الله'),
  array('id' => '693','translator_name' => 'د. اسحق زكريا '),
  array('id' => '694','translator_name' => 'سامح فكري حنا'),
  array('id' => '695','translator_name' => 'حسام أبو سعدة'),
  array('id' => '696','translator_name' => 'مايكل رأفت'),
  array('id' => '697','translator_name' => 'د. عبد الجواد خليفة أبو زيد'),
  array('id' => '698','translator_name' => 'موريس وهيب - أندرو وهيب '),
  array('id' => '699','translator_name' => 'عبلة عودة'),
  array('id' => '700','translator_name' => 'الحارث النبهان'),
  array('id' => '701','translator_name' => 'صفاء إسماعيل مرسي'),
  array('id' => '702','translator_name' => 'د. طه ربيع عدوي- رانيا شعبان الصايم'),
  array('id' => '703','translator_name' => 'الأب بولص طعمه'),
  array('id' => '704','translator_name' => 'أمجد بشاره'),
  array('id' => '705','translator_name' => 'بيشوي جرجس'),
  array('id' => '706','translator_name' => 'د. محمد أحمد محمود خطاب'),
  array('id' => '707','translator_name' => 'أمجد عنتر'),
  array('id' => '708','translator_name' => 'أمين سلامة'),
  array('id' => '709','translator_name' => 'مصطفي عبد المعبود - سيد منصور '),
  array('id' => '710','translator_name' => 'د. شهاب الدين السواري'),
  array('id' => '711','translator_name' => 'د. شهاب الدين السواري- آدم رمزي'),
  array('id' => '712','translator_name' => 'د. حامد عبد العزيز الفقي - د. سيد خيرالله'),
  array('id' => '713','translator_name' => 'صموئيل ن. صليب'),
  array('id' => '714','translator_name' => 'خليل الشيخ'),
  array('id' => '715','translator_name' => 'نرمين سمير'),
  array('id' => '716','translator_name' => 'محمد عثمان'),
  array('id' => '717','translator_name' => 'معن عاقل'),
  array('id' => '718','translator_name' => 'وليد أبو بكر'),
  array('id' => '719','translator_name' => 'نولة درويش'),
  array('id' => '720','translator_name' => 'أمل محمد بكري'),
  array('id' => '721','translator_name' => 'باسم سمير فرج'),
  array('id' => '723','translator_name' => 'عبد الله السيد عسكر'),
  array('id' => '724','translator_name' => 'P.T.W.'),
  array('id' => '725','translator_name' => 'أدهم وهيب مطر '),
  array('id' => '726','translator_name' => 'د. ياسمين حداد - د. موفق الحمداني - د. فارس حلمي'),
  array('id' => '727','translator_name' => 'متيم الضايع'),
  array('id' => '728','translator_name' => 'د. شهاب الدين الهواري - رؤوم بهاء الدين'),
  array('id' => '729','translator_name' => ' ندي ممدوح سلامة'),
  array('id' => '730','translator_name' => 'د. سليمان الغديات '),
  array('id' => '731','translator_name' => 'سعيد'),
  array('id' => '732','translator_name' => 'محمود عيسي - نوار العبد الله'),
  array('id' => '733','translator_name' => 'مدحت طه'),
  array('id' => '734','translator_name' => 'غراء مهنا'),
  array('id' => '735','translator_name' => 'عليه عبد السلام'),
  array('id' => '736','translator_name' => 'موريس وهيب - بولا نبيل'),
  array('id' => '737','translator_name' => 'هبه سامي علي'),
  array('id' => '738','translator_name' => 'محمد محمد مدين'),
  array('id' => '739','translator_name' => 'د. أمجد عنتر'),
  array('id' => '740','translator_name' => 'عادل دكري'),
  array('id' => '741','translator_name' => 'د. جوليا حنا'),
  array('id' => '742','translator_name' => 'أرجوان بنت سليمان'),
  array('id' => '743','translator_name' => 'عمرو الشريف'),
  array('id' => '744','translator_name' => 'أحمد موسي'),
  array('id' => '745','translator_name' => 'قدري حفني - عبد اللطيف خليفة- فؤاد أبو المكارم'),
  array('id' => '746','translator_name' => 'آراك الشوشان'),
  array('id' => '747','translator_name' => 'الأب جون جبرائيل الدومينيكاني '),
  array('id' => '748','translator_name' => 'سعيد الحسنيه'),
  array('id' => '749','translator_name' => 'د. عادل مصطفي'),
  array('id' => '750','translator_name' => 'المركز القومي للترجمة'),
  array('id' => '751','translator_name' => 'جون جبرائيل الدومنبكاني'),
  array('id' => '752','translator_name' => 'جورج برشين'),
  array('id' => '753','translator_name' => 'أحمد محمود هويدي'),
  array('id' => '754','translator_name' => 'عبد الله بديع فاضل'),
  array('id' => '755','translator_name' => 'د. محمد السبحي'),
  array('id' => '756','translator_name' => 'د, وفاء طارق'),
  array('id' => '757','translator_name' => 'د. بدر محمد العدل'),
  array('id' => '758','translator_name' => 'أ.د. محمد حمدي الحجار'),
  array('id' => '759','translator_name' => 'أ.د. علاء الدين كفافي - د. فؤاد الدواش'),
  array('id' => '760','translator_name' => 'زياد إبراهيم'),
  array('id' => '761','translator_name' => 'جين محيي'),
  array('id' => '762','translator_name' => 'د. سامي بن صلاح الفوجان - د. تيسير الياس شواش'),
  array('id' => '763','translator_name' => 'نحبه من المترجمين'),
  array('id' => '764','translator_name' => 'ق. وجيه يوسف'),
  array('id' => '765','translator_name' => 'جويس فيكتور صموئيل'),
  array('id' => '766','translator_name' => 'دوار'),
  array('id' => '767','translator_name' => 'عبد المقصود عبد الكريم'),
  array('id' => '768','translator_name' => 'هاني ميلاد'),
  array('id' => '769','translator_name' => 'عمر صلاح سيد'),
  array('id' => '770','translator_name' => 'فادي حليسو  اليسوعي'),
  array('id' => '771','translator_name' => 'فادي غطاس'),
  array('id' => '772','translator_name' => 'ماريان حلمي'),
  array('id' => '773','translator_name' => 'عيسي عبدالله'),
  array('id' => '774','translator_name' => 'نادين نصرالله'),
  array('id' => '775','translator_name' => 'محمد فضل'),
  array('id' => '776','translator_name' => 'د. أحمد موسي '),
  array('id' => '777','translator_name' => 'فريق دوبامين للخدمات النفسية و الإجتماعية '),
  array('id' => '778','translator_name' => 'ق. مينا القمص اسحق - موريس وهيب '),
  array('id' => '779','translator_name' => 'أحمد حسن'),
  array('id' => '780','translator_name' => 'محمد مشكاف'),
  array('id' => '781','translator_name' => 'ماريان رأفت الملاح'),
  array('id' => '782','translator_name' => 'ماريانا  صموئيل كتكوت'),
  array('id' => '783','translator_name' => 'ق. سامح إبراهيم'),
  array('id' => '784','translator_name' => 'منال زكريا حسين - محمد سعد محمد'),
  array('id' => '785','translator_name' => 'زينب مبارك'),
  array('id' => '786','translator_name' => 'أحمد الشيمي'),
  array('id' => '787','translator_name' => 'د. حمادة إبراهيم'),
  array('id' => '788','translator_name' => 'نعيم عطية'),
  array('id' => '789','translator_name' => 'عصام وجيه عطية - كيرلس إيراهيم سعد'),
  array('id' => '790','translator_name' => 'د. راقية الرويك - د. أحمد موسي - د. وائل يوسف'),
  array('id' => '791','translator_name' => 'د. إبراهيم يونس - د. هالة السيد'),
  array('id' => '792','translator_name' => 'د. سامر جميل رضوان'),
  array('id' => '793','translator_name' => 'محمود ايمن'),
  array('id' => '794','translator_name' => 'محمود غنيم'),
  array('id' => '795','translator_name' => 'سمر نجاح'),
  array('id' => '796','translator_name' => 'يزن غطاس'),
  array('id' => '797','translator_name' => 'عباس المفرجي'),
  array('id' => '798','translator_name' => 'سارة أزهر الجوهري - أحمد عزيز سامي'),
  array('id' => '799','translator_name' => 'د. محمد ياسر حسكي - بسام عبدي'),
  array('id' => '800','translator_name' => 'م. ناجي تكلا'),
  array('id' => '801','translator_name' => 'نادر جوزيف'),
  array('id' => '802','translator_name' => 'سامح عبد الكريم صالح'),
  array('id' => '803','translator_name' => 'محمد ابراهيم الجندي'),
  array('id' => '804','translator_name' => 'إسراء جاد'),
  array('id' => '805','translator_name' => 'عصام سامي'),
  array('id' => '806','translator_name' => 'د. إيمان هنداوي'),
  array('id' => '807','translator_name' => 'د. مريم ميلاد- د. ريمون يوسف'),
  array('id' => '808','translator_name' => 'محمدعبد النبي'),
  array('id' => '809','translator_name' => 'حجاج أبو جبر'),
  array('id' => '810','translator_name' => 'ماسنر ميديا'),
  array('id' => '811','translator_name' => 'مايكل بقطر داود - د. ممدوج صدقي زخاري'),
  array('id' => '812','translator_name' => 'عزيزه محمد السيد'),
  array('id' => '813','translator_name' => 'حمزه ماهر عبد الرحمن '),
  array('id' => '814','translator_name' => 'عمار المصري'),
  array('id' => '815','translator_name' => 'بتول مسلماني'),
  array('id' => '816','translator_name' => 'طلال العمري - هدي متبولي')
          );
          
    
        foreach($translators as $translator){
            Translator::create($translator);
        }
    }
}
